/** Public feature inventory. Beta means development builds, not a purchasable public feature. */
export type FeatureGroupId = "timing" | "connection" | "review" | "training" | "sharing" | "beta";
export type ProductFeature = {id: string; title: string; description: string; group: FeatureGroupId; status: "ios" | "beta"};
export const featureGroups: {id: FeatureGroupId; title: string; description: string}[] = [
  {id: "timing", title: "Timing & starts", description: "Define the effort, the start and the finish."},
  {id: "connection", title: "Connected sessions", description: "Bring your phones together as a set of timing gates."},
  {id: "review", title: "Evidence & results", description: "Understand the result and keep the context."},
  {id: "training", title: "Athletes & training", description: "Keep every athlete, repetition and session organized."},
  {id: "sharing", title: "Sharing & everyday use", description: "Take the session with you."},
  {id: "beta", title: "Apple Watch & agility", description: "Watch starts, running dynamics and landscape sprint and agility timing."},
];
export const productFeatures: ProductFeature[] = [
  {id:"automatic",group:"timing",status:"ios",title:"Automatic camera gates",description:"Position a camera at a measured line. A detected crossing records the event used to time your run."},
  {id:"flying",group:"timing",status:"ios",title:"Flying starts",description:"Build speed before the start phone. The timed interval begins at the first gate and ends at the finish gate."},
  {id:"touch",group:"timing",status:"ios",title:"Touch-release starts",description:"Hold a finger on the start phone, then lift to begin. This times from finger release; it is not a block reaction-time measurement."},
  {id:"countdown",group:"timing",status:"ios",title:"Countdown starts",description:"A countdown gives you an audible starting cue. The interval begins on the cue and includes the athlete’s response."},
  {id:"voice",group:"timing",status:"ios",title:"Spoken start commands",description:"Train with a spoken starting sequence. Timing begins at GO, with an automatic camera finish."},
  {id:"in-frame",group:"timing",status:"ios",title:"In-frame starts",description:"Begin at the start phone’s front-camera gate, then cross the displayed line to start the run."},
  {id:"splits",group:"timing",status:"ios",title:"Split times & average speed",description:"Add intermediate gates to see individual segments as well as the total. Average speed uses the distance you measured."},
  {id:"solo-laps",group:"timing",status:"ios",title:"Solo Laps",description:"Use one phone at a line you cross repeatedly. The first crossing starts timing; later crossings produce lap times and photos."},
  {id:"multi-phone",group:"connection",status:"ios",title:"Start, split & finish phones",description:"Create one session and join it from your other phones. Place each phone at its assigned gate before arming."},
  {id:"aware",group:"connection",status:"ios",title:"Wi-Fi Aware",description:"Use a nearby peer-to-peer connection on compatible phones and operating systems. Availability depends on the hardware and software of both devices."},
  {id:"bluetooth",group:"connection",status:"ios",title:"Bluetooth connection",description:"A supported connection option for nearby phones. Range, interference and device compatibility still matter; confirm readiness before running."},
  {id:"clocks",group:"connection",status:"ios",title:"Synchronized event timing",description:"The session aligns phone clocks so elapsed time comes from recorded events, rather than the time a wireless message appears on screen."},
  {id:"offline",group:"connection",status:"ios",title:"Local timing without internet",description:"Supported nearby routes can time locally without a mobile data connection. Keep the required radios enabled; online features still need internet."},
  {id:"ready",group:"connection",status:"ios",title:"Gate readiness & recovery",description:"See connection and gate readiness before a run. If a phone is interrupted, restore its position and wait for a ready session before the next effort."},
  {id:"photos",group:"review",status:"ios",title:"Start & finish photos",description:"Keep crossing images with the run so you can inspect the start, finish and available split evidence."},
  {id:"adjust",group:"review",status:"ios",title:"Photo review & adjustments",description:"Open the available crossing evidence and review or adjust its timing. Keep the same review method when comparing repeated tests."},
  {id:"history",group:"review",status:"ios",title:"Session history",description:"Revisit saved sessions and their runs, dates, distances, start methods, athletes, times and speed."},
  {id:"bests",group:"review",status:"ios",title:"Personal bests & comparisons",description:"Follow your progress across comparable efforts. A flying start and a cue start measure different intervals; keep method and distance consistent."},
  {id:"edit",group:"review",status:"ios",title:"Manage saved results",description:"Review, edit or remove results in history. Keep useful attempts organized and retain the context needed to interpret them."},
  {id:"athletes",group:"training",status:"ios",title:"Athlete profiles",description:"Assign runs to the right person and keep individual results organized during shared training sessions."},
  {id:"templates",group:"training",status:"ios",title:"Sprint templates",description:"Start from familiar acceleration, flying sprint and testing distances, including 10 m, 30 m and the 40-yard dash."},
  {id:"custom",group:"training",status:"ios",title:"Custom sessions & distances",description:"Choose the distance, start method and gate arrangement to match your training. Measure the real course before recording."},
  {id:"repeat",group:"training",status:"ios",title:"Repeated runs & repeat session",description:"Keep repetitions together and return to a saved session setup for your next workout."},
  {id:"units",group:"training",status:"ios",title:"Distance & speed units",description:"Use the distance and speed units available in the app, with distance conversion when planning a course."},
  {id:"csv",group:"sharing",status:"ios",title:"CSV data export",description:"Export a session or your history with dates, distances, run numbers, times, speed, athlete, start type and mode."},
  {id:"cards",group:"sharing",status:"ios",title:"Result & session cards",description:"Create a shareable image of a result or session for a coach, training group or your own record."},
  {id:"video",group:"sharing",status:"ios",title:"Video timing overlays",description:"Add a timing overlay to a video and export the result. Keep the original video for your own review."},
  {id:"sync",group:"sharing",status:"ios",title:"Account & cloud sync",description:"Save supported session data to your account and retry pending uploads when connectivity returns. Landscape and Watch-start beta evidence currently stays local."},
  {id:"appearance",group:"sharing",status:"ios",title:"Appearance & language options",description:"Choose the appearance, language and display options available in the app. A large timing display keeps the current session readable."},
  {id:"watch-start",group:"beta",status:"beta",title:"Apple Watch starts",description:"Movement, ready-set-go and external-sound modes are being tested. Wrist movement is an estimate of onset, not a certified block reaction measurement."},
  {id:"watch-gates",group:"beta",status:"beta",title:"Watch with two or more phones",description:"For Watch-generated starts, the paired host/start iPhone passes the start to the other timing phones. The Watch connects to its paired iPhone, not directly to every gate."},
  {id:"watch-results",group:"beta",status:"beta",title:"Watch results & next repetition",description:"View the completed result on your wrist and continue the session. Time delivery is separate from whether enough motion samples exist for dynamics."},
  {id:"watch-dynamics",group:"beta",status:"beta",title:"Running dynamics",description:"Explore available cadence, step frequency and estimated step/stride length within a timed run or segment. Results depend on Watch model and sample quality."},
  {id:"landscape",group:"beta",status:"beta",title:"Landscape one-phone sprints",description:"A fixed, side-on camera observes the whole measured course. Standing mode starts at body movement; flying mode starts at the 0 m crossing."},
  {id:"agility",group:"beta",status:"beta",title:"5-10-5 pro agility",description:"Three lines spaced 5 yards apart. Start at centre, touch both outside lines and finish through centre; the first centre return is a split. Both touches need video review."},
  {id:"shuttle",group:"beta",status:"beta",title:"Out-and-back drills",description:"Run to a far line and return through the start. Standing and flying options use distinct start anchors; the far-line touch requires video review."},
  {id:"solo-video",group:"beta",status:"beta",title:"Solo run video & refinement",description:"Save the run video, review the detected anchors and see whether analysis is complete. Review-only or unconfirmed results do not establish a personal best."},
];
