import Link from 'next/link';
import type {Metadata} from 'next';
import JumpLegal from '@/components/jump/JumpLegal';
export const metadata:Metadata={title:'TrackJump Terms of Service',description:'Terms for using TrackJump jump testing, subscriptions, recordings and athlete profiles.',alternates:{canonical:'https://mytrackspeed.com/jump/terms'}};
export default function Page(){return <JumpLegal title="Terms of Service" intro="These terms apply to the TrackJump app and related services provided by Athlete Mindset Inc. By using TrackJump, you agree to these terms and the applicable Apple end-user license terms.">
<h2>1. Who can use TrackJump</h2><p>You must be at least 13 to create an account, and have a parent or guardian&apos;s permission if you are under 18. Provide accurate account information and keep sign-in credentials secure. You are responsible for obtaining permission before recording another person or storing their athlete information.</p>
<h2>2. Training measurements</h2><p>TrackJump estimates jump height and related performance measures from camera evidence. Results depend on the device, lighting, frame rate, framing, technique and visibility of takeoff and landing. Some results require review or may be unavailable. Comparisons should use matching protocols and measurement methods.</p><p>The app is for training information. It is not a medical device, diagnosis, injury-risk assessment, certified competition measurement or substitute for a force plate or professional assessment. Do not make rehabilitation or medical decisions solely from a jump score or asymmetry percentage. Independently validate measurements when precise accuracy is necessary.</p>
<h2>3. Safe use</h2><p>Warm up, use a stable camera support and choose a clear, level area with enough headroom and a suitable landing surface. Select tests appropriate to the athlete&apos;s ability. Stop if a test causes pain or feels unsafe. Drop and single-leg tests may require qualified supervision. You remain responsible for the activity and environment.</p>
<h2>4. Your content and permission to process it</h2><p>You keep ownership of your recordings and athlete data. You grant us the limited permission needed to store, process, back up and deliver the content you choose to put into the service. This permission does not allow us to sell your recordings or use them to train general-purpose AI models. You control exports and sharing. Our <Link href="/jump/privacy">Privacy Policy</Link> explains data handling.</p>
<h2>5. Our app and intellectual property</h2><p>TrackJump&apos;s original code, visual assets, interface artwork, text and branding are owned by Athlete Mindset Inc. or its licensors. Your license to use the app does not transfer those rights.</p><p>Except where applicable law or an applicable open-source license permits otherwise, you may not copy or redistribute our code or protected assets; create derivative works from them; decompile, reverse engineer or attempt to obtain nonpublic source code; remove ownership notices; impersonate TrackJump; bypass access controls; or resell or sublicense the app without permission. Independent ideas, facts and functionality are subject to the rights provided by applicable law; these terms do not create ownership over them.</p><p>Normal use by a coach in their training sessions is permitted. These restrictions do not prevent sharing your own exported results and videos using the app&apos;s sharing tools. Third-party software remains subject to its own license terms.</p>
<h2>6. Subscriptions and payments</h2><p>If you choose a paid plan, the app shows the exact price, billing period and included access before confirmation. Purchases are charged to your Apple Account. Auto-renewable subscriptions renew unless canceled at least 24 hours before the current period ends. Apple&apos;s purchase confirmation is the authoritative disclosure for the transaction.</p><p>You can manage or cancel in <a href="https://apps.apple.com/account/subscriptions">App Store subscription settings</a> and restore purchases in TrackJump&apos;s Profile. Cancellation normally leaves access active until the paid period ends. Refund requests are handled through <a href="https://reportaproblem.apple.com">Apple</a> and applicable consumer law. Deleting the app or your account does not cancel a subscription. TrackSpeed and TrackJump purchases are separate unless an offer explicitly states otherwise.</p>
<h2>7. Account deletion and service access</h2><p>Delete your account directly in <strong>Profile → Delete account</strong>. Deletion removes the active account and associated owned cloud data and cannot be undone. Export any records you need beforehand. See <Link href="/jump/delete-account">deletion instructions</Link> for subscriptions and local copies. We may restrict use that is unlawful, abusive or compromises service security.</p>
<h2>8. Availability and responsibility</h2><p>We work to provide a reliable service but do not promise uninterrupted availability, compatibility with every environment, or a particular measurement accuracy. Keep an independent export of records that are important to you. Features can change as device capabilities, the service and legal requirements change.</p><p>To the extent permitted by law, the service is provided as available without additional warranties, and we are not liable for indirect losses resulting from its use. Nothing in these terms excludes rights or liabilities that cannot legally be excluded, including applicable consumer protections.</p>
<h2>9. Apple terms</h2><p>The <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple Standard End User License Agreement</a> applies to the App Store app. These terms address TrackJump&apos;s service and do not reduce rights under that agreement or applicable law. Apple is not responsible for providing TrackJump support or resolving your service questions.</p>
<h2>10. Changes and contact</h2><p>We will update the date on this page when the terms change and provide notice of material changes where required. Contact <a href="mailto:support@mytrackspeed.com">support@mytrackspeed.com</a> with questions about TrackJump or these terms.</p>
</JumpLegal>}
