"use client";

import { useState } from "react";
import { Cross2Icon, MagnifyingGlassIcon, ArrowTopRightIcon } from "@radix-ui/react-icons";
import { featureGroups, productFeatures, type FeatureGroupId } from "@/lib/product-features";

export default function FeatureGuide() {
  const [group,setGroup]=useState<FeatureGroupId|"all">("all");
  const [query,setQuery]=useState("");
  const needle=query.trim().toLocaleLowerCase("en");
  const filtered=productFeatures.filter(f=>(group==="all"||f.group===group)&&`${f.title} ${f.description}`.toLocaleLowerCase("en").includes(needle));
  return <div className="feature-guide">
    <div className="mb-8 flex flex-col justify-between gap-5 border-y border-[var(--border-light)] py-6 sm:flex-row sm:items-end"><div className="w-full sm:max-w-sm"><label htmlFor="feature-search" className="mb-2 block text-xs font-medium">Find a feature</label><div className="relative"><MagnifyingGlassIcon className="absolute start-4 top-3.5 size-5 text-muted" aria-hidden="true"/><input type="search" id="feature-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try “splits”, “video” or “Watch”" className="min-h-12 w-full rounded-lg border border-[var(--border-light)] bg-white pe-11 ps-12 text-sm outline-offset-4"/>{query&&<button type="button" aria-label="Clear search" onClick={()=>setQuery("")} className="absolute end-1 top-1 flex size-10 items-center justify-center"><Cross2Icon aria-hidden="true"/></button>}</div></div><p role="status" aria-live="polite" className="text-xs text-muted">{filtered.length} of {productFeatures.length} features</p></div>
    <div className="mb-12 flex flex-wrap gap-2" aria-label="Feature categories">{[{id:"all",title:"All features"},...featureGroups].map(item=><button key={item.id} type="button" onClick={()=>setGroup(item.id as FeatureGroupId|"all")} aria-pressed={group===item.id} className={`min-h-10 rounded-full border px-4 py-2 text-xs font-medium transition-colors ${group===item.id ? "border-foreground bg-foreground text-white" : "border-[var(--border-light)] text-muted hover:border-foreground hover:text-foreground"}`}>{item.title}</button>)}</div>
    {filtered.length===0 ? <div className="rounded-2xl bg-[var(--bg-warm)] px-8 py-16 text-center"><h2 className="text-2xl font-medium tracking-tight">No matching features</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted">Try a broader word or reset the filters to see the complete guide.</p><button type="button" className="marketing-button mt-6" onClick={()=>{setGroup("all");setQuery("");}}>Reset filters</button></div> : featureGroups.map(category=>{const items=filtered.filter(f=>f.group===category.id);if(!items.length)return null;return <section id={category.id} key={category.id} className="mb-16 grid gap-8 lg:grid-cols-[0.7fr_1.3fr] lg:gap-16"><div><h2 className="text-2xl font-medium tracking-tight">{category.title}</h2><p className="mt-3 max-w-sm text-sm leading-6 text-muted">{category.description}</p></div><div className="grid gap-x-8 sm:grid-cols-2">{items.map(item=><article key={item.id} id={item.id===category.id?undefined:item.id} className="border-t border-[var(--border-light)] py-6">{item.status==="ios"&&<div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--brand)]"><span className="size-1 rounded-full bg-current" aria-hidden="true"/>iOS feature</div>}<h3 className="text-base font-semibold tracking-tight">{item.title}</h3><p className="mt-3 text-sm leading-7 text-muted">{item.description}</p></article>)}</div></section>;})}
    <aside className="border-t border-[var(--border-light)] pt-8 text-sm leading-7 text-muted">Plans and availability can change. Check the app for current purchase terms and the features available to your account. <a className="inline-flex items-center gap-1 text-foreground underline underline-offset-4" href="https://apps.apple.com/us/app/trackspeed-sprint-timer/id6757509163">View the App Store listing<ArrowTopRightIcon className="size-3.5" aria-hidden="true"/></a></aside>
  </div>;
}
