from pathlib import Path
import copy,json
root=Path(__file__).resolve().parents[3]
en=json.loads((root/'messages/en/marketing.json').read_text())
paths={
'meta':'title description',
'nav':'guide download close more guideLanguage',
'hero':'kicker title accent description secondary availability proof imageAlt example imageCaption sports',
'facts':'0.label 1.label 2.label',
'modes':'kicker title description diagramLabel start split finish phone turn centre lap beta available watchLabel',
'gates':'tab title body steps.0 steps.1 steps.2 requirement',
'solo':'tab title body steps.0 steps.1 steps.2 requirement',
'watch':'tab title body steps.0 steps.1 steps.2 requirement',
'agility':'tab title body steps.0 steps.1 steps.2 requirement',
'evidence':'kicker title body items.0 items.1 items.2 link caption',
'starts':'kicker title description items.0.title items.0.body items.1.title items.1.body items.2.title items.2.body items.3.title items.3.body items.4.title items.4.body',
'workflow':'kicker title guide items.0.title items.0.body items.1.title items.1.body items.2.title items.2.body items.3.title items.3.body items.3.body_PLACEHOLDER',
'beta':'kicker title body note link',
'founder':'kicker title body link imageAlt',
'faq':'title items.0.question items.0.answer items.1.question items.1.answer items.2.question items.2.answer items.3.question items.3.answer items.4.question items.4.answer',
'cta':'kicker title body note',
'footer':'tagline moreApps availability'
}
paths['workflow']='kicker title guide '+' '.join(f'items.{i}.{k}' for i in range(6) for k in ['title','body'])
def save(locale,pack):
 assert set(pack)==set(paths),(locale,set(paths)-set(pack))
 data=copy.deepcopy(en)
 for section,fields in paths.items():
  values=pack[section].split('|'); fields=fields.split()
  assert len(values)==len(fields),(locale,section,len(values),len(fields))
  base='modes.'+section if section in ['gates','solo','watch','agility'] else section
  for field,value in zip(fields,values):
   keys=(base+'.'+field).split('.');obj=data
   for key in keys[:-1]:obj=obj[int(key)] if isinstance(obj,list) else obj[key]
   key=keys[-1];obj[int(key) if isinstance(obj,list) else key]=value
 (root/f'messages/{locale}/marketing.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 print(locale, sum(len(v.split()) for v in paths.values()),'translated fields')

save('nb',{
'meta':'Sprinttidtaking. Med telefonen.|Automatisk sprinttidtaking, trådløse porter, solorunder, bildeanalyse, utøverprofiler og økthistorikk. Se også forhåndsvisning av Apple Watch og agility.',
'nav':'Alle funksjoner|Last ned TrackSpeed|Lukk meny|Utforsk|Funksjonsguiden er på engelsk',
'hero':'For arbeidet mellom konkurransene|Sprinttidtaking.|Med telefonen.|Gjør telefonene du allerede har til et tidtakingssystem. Registrer start, mellomtider og mål. Følg fremgangen, ett løp av gangen.|Finn ditt oppsett|For iPhone og iPad · Gratis nedlasting, kjøp i appen|Utviklet av OL-utøver Sondre Guttormsen|TrackSpeed viser en flyvende sprint med start- og målbilder|Inne i TrackSpeed|En tid du kan gå tilbake og kontrollere.|Sprinttrening / Flyvende sprint / Tilløp / Lagtesting',
'facts':'telefon for solorunder|telefoner for tilkoblede porter|måter å starte en sprint på',
'modes':'Din økt. Ditt oppsett.|Tidtaking som passer treningen din.|Tren alene, koble sammen porter eller se hva vi utvikler videre.|Illustrasjon av banen, ikke i målestokk|Start|Mellomtid|Mål|Telefon|Vending|Midten|Rundelinje|Under utvikling|Tilgjengelig på iOS|Klokke',
'gates':'Tilkoblede porter|Én økt. Alle mellomtidene.|Plasser telefoner ved start og mål. Legg til en telefon for mellomtid for å se hvordan farten endrer seg.|Mål opp banen og plasser telefonene.|Opprett eller bli med i samme økt, og vent til alle portene er klare.|Løp gjennom. Se tiden og passeringsbildene sammen.|2+ telefoner · Oppmålt bane · Stabile stativer',
'solo':'Solorunder|Bare deg. Én telefon.|Plasser kameraet ved en linje du passerer flere ganger. Første passering starter økten, og de neste gir rundetid og bilde.|Fest telefonen ved en tydelig markert linje.|Velg Solo Laps og kontroller kamerabildet.|Kryss samme linje for hver runde eller retur.|1 telefon · Gjentatte passeringer av samme linje',
'watch':'Apple Watch|Ha økten på håndleddet.|Vi utvikler klokkestart, resultatvisning og løpsdynamikk. Den sammenkoblede iPhonen kobler klokken til tidtakingsøkten.|Koble klokken til vertens start-iPhone for klokkestart.|Bruk andre telefoner til mål og eventuelle mellomtider.|Se tiden, og utforsk tilgjengelige bevegelsesdata.|Utviklingsversjon · Ikke i den offentlige appen ennå',
'agility':'Agility og solosprint|Ett kamera. Hele øvelsen.|Liggende kameratidtaking utvikles for stående og flyvende sprint, 5-10-5 og løp frem og tilbake. Hele banen må være synlig.|For 5-10-5: marker tre linjer med 5 yards mellom hver.|Start i midten, berør begge ytterlinjene og returner til midten.|Første retur gjennom midten er en mellomtid. Kontroller begge berøringene på video.|Utviklingsversjon · Stativ og videokontroll av vendinger',
'evidence':'Mer enn et tall|Se hva som stoppet klokken.|Automatiske kamerapasseringer gir hvert løp en tydelig start og slutt. Åpne bildene, kontroller linjen og behold resultatet i økten.|Automatisk passeringsdeteksjon|Dokumentasjon av start, mellomtid og mål|Bildekontroll og tidsjustering|Slik fungerer tidtakingen|Appbilde med eksempeldata fra en økt',
'starts':'Start på dine premisser|Fem måter å komme i gang på.|Velg startmetoden som passer testen. Sammenlign resultater med samme startmetode.|Flyvende start|Bygg fart før første port. Passering av startlinjen begynner den målte sonen.|Slipp skjermen|Hold fingeren på starttelefonen. Tiden starter når du løfter den.|Nedtelling|En nedtelling avsluttes med et lydsignal. Tiden starter på signalet og inkluderer reaksjonen din.|Talekommando|Følg de talte startkommandoene. Tiden starter på GO.|Start i bildet|Stå ved starttelefonens frontkameraport. Kryss linjen på skjermen for å starte.',
'workflow':'Fra første repetisjon til neste økt|Treningen din, samlet.|Utforsk alle funksjonene|Mellomtider og snittfart|Mål hele løpet og delstrekningene. Se snittfarten for den oppmålte distansen.|Utøvere og lag|Knytt løp til utøverprofiler og hold orden på gruppetreningen.|Historikk og personlige rekorder|Finn tidligere økter, sammenlign like tester og følg fremgangen.|Maler og gjentatte økter|Velg en sprintmal eller egen distanse. Gjenbruk et lagret oppsett.|CSV, kort og video|Eksporter øktdata, del et resultatkort eller lag video med tidtakingsoverlegg.|Trådløs og frakoblet tidtaking|Koble nærliggende telefoner via støttede lokale forbindelser. Lagre resultatene og synkroniser støttede øktdata når du er på nett.',
'beta':'Under utvikling|Neste kapittel i treningen din.|Start med Apple Watch og løpsdynamikk. Solosprint med liggende telefon. Agility for fotball, inkludert 5-10-5 og løp frem og tilbake.|Funksjonene testes fysisk og er ikke i den offentlige appen ennå. Ingen lanseringsdato er lovet.|Se utviklingsforhåndsvisningen',
'founder':'Skapt på friidrettsbanen|Bygget av en utøver som bruker det.|Sondre Guttormsen er olympisk stavhopper og grunnlegger og utvikler av TrackSpeed. Målet er praktisk: gjøre gjentakbar sprinttesting enklere i den daglige treningen.|Møt grunnleggeren|Sondre Guttormsen konkurrerer i stavsprang',
'faq':'Før ditt første løp.|Kan jeg bruke bare én telefon?|Ja. Solo Laps registrerer gjentatte passeringer av én kameralinje. Separate start- og målsteder bruker tilkoblede telefoner. Liggende solosprint og agility er under utvikling.|Trenger jeg Wi-Fi eller internett?|Støttede lokale forbindelser kan ta tiden uten internett. Wi-Fi Aware krever kompatibel maskinvare og programvare; Bluetooth er et annet alternativ. Skyfunksjoner krever nett.|Hvor nøyaktig er det?|Resultatene avhenger av bildefrekvens, lys, plassering, startmetode og klokkesynkronisering. Antall desimaler er ingen nøyaktighetsgaranti. Bruk et stabilt oppsett og kontroller passeringsbildene. TrackSpeed er for trening, ikke offisiell konkurransetidtaking.|Fungerer det med Apple Watch eller Android?|Den offentlige opplevelsen beskrevet her er for iPhone og iPad. Klokkefunksjoner, liggende agility og Android er under utvikling. Vi lover ikke identiske funksjoner på alle plattformer.|Hva koster TrackSpeed?|Appen er gratis å laste ned, med kjøp i appen. Se appen for abonnementer, priser, prøvevilkår og funksjoner i din region.',
'cta':'Ta det med på neste økt|Sett linjen. Løp ditt beste.|Neste treningsøkt er et godt sted å begynne.|iPhone og iPad · Kjøp i appen',
'footer':'Sprinttidtaking for arbeidet du legger ned.|Mer fra utvikleren|Apple Watch og liggende agility: under utvikling.'})

save('de',{
'meta':'Sprintzeiten. Mit deinem Handy.|Automatische Sprintzeitmessung, drahtlose Messpunkte, Solo-Runden, Fotoprüfung, Athletenprofile und Trainingsverlauf. Mit Vorschau auf Watch und Agility.',
'nav':'Alle Funktionen|TrackSpeed laden|Menü schließen|Entdecken|Funktionsübersicht auf Englisch',
'hero':'Für das Training zwischen den Wettkämpfen|Sprintzeiten.|Mit deinem Handy.|Verwandle deine vorhandenen Handys in ein Zeitmesssystem. Erfasse Starts, Zwischenzeiten und Zieleinläufe. Verfolge deinen Fortschritt, Lauf für Lauf.|Finde dein Setup|Für iPhone & iPad · Kostenloser Download, In-App-Käufe|Entwickelt von Olympiateilnehmer Sondre Guttormsen|TrackSpeed mit fliegendem Sprint sowie Start- und Zielfotos|Einblick in TrackSpeed|Eine Zeit, die du überprüfen kannst.|Sprinttraining / Fliegende Sprints / Anläufe / Teamtests',
'facts':'Handy für Solo-Runden|Handys für verbundene Messpunkte|Startmethoden für deinen Sprint',
'modes':'Dein Training. Dein Setup.|Zeitmessung, die zu deinem Training passt.|Trainiere allein, verbinde Messpunkte oder entdecke unsere nächsten Entwicklungen.|Schematische Strecke, nicht maßstabsgetreu|Start|Zwischenzeit|Ziel|Handy|Wende|Mitte|Rundenlinie|In Entwicklung|Auf iOS verfügbar|Uhr',
'gates':'Verbundene Messpunkte|Ein Training. Jede Zwischenzeit.|Stelle Handys an Start und Ziel auf. Ergänze einen Messpunkt, um die Geschwindigkeit über einzelne Abschnitte zu verfolgen.|Miss die Strecke aus und positioniere die Handys.|Erstelle eine gemeinsame Einheit und warte, bis alle Messpunkte bereit sind.|Laufe durch. Prüfe Zeit und Fotos zusammen.|2+ Handys · Ausgemessene Strecke · Stabile Halterungen',
'solo':'Solo-Runden|Nur du. Ein Handy.|Stelle die Kamera an eine Linie, die du mehrfach überquerst. Die erste Überquerung startet, jede weitere erfasst eine Rundenzeit und ein Foto.|Befestige das Handy neben einer klar markierten Linie.|Wähle Solo Laps und prüfe das Kamerabild.|Überquere bei jeder Runde oder Rückkehr dieselbe Linie.|1 Handy · Wiederholtes Überqueren derselben Linie',
'watch':'Apple Watch|Dein Training am Handgelenk.|Wir entwickeln Watch-Starts, Ergebnisanzeige und Laufdynamik. Das gekoppelte iPhone verbindet die Uhr mit der Zeiteinheit.|Kopple die Watch für Watch-Starts mit dem Host-/Start-iPhone.|Nutze weitere Handys für Ziel und Zwischenzeiten.|Prüfe die Zeit und verfügbare Bewegungsdaten.|Entwicklungsvorschau · Noch nicht in der öffentlichen App',
'agility':'Agility & Solo-Sprints|Eine Kamera. Die ganze Übung.|Querformat-Zeitmessung für stehende und fliegende Sprints, 5-10-5 und Pendelläufe wird entwickelt. Die gesamte Strecke muss sichtbar sein.|Markiere für 5-10-5 drei Linien im Abstand von 5 Yards.|Starte in der Mitte, berühre beide Außenlinien und kehre zur Mitte zurück.|Die erste Rückkehr durch die Mitte ist eine Zwischenzeit. Prüfe beide Berührungen im Video.|Entwicklungsvorschau · Stativ und Videoprüfung der Wenden',
'evidence':'Mehr als eine Zahl|Sieh, was die Uhr gestoppt hat.|Automatische Kameraereignisse geben jedem Lauf einen klaren Start und Abschluss. Öffne die Fotos, prüfe die Linie und behalte das Ergebnis in der Einheit.|Automatische Überquerungserkennung|Start-, Zwischenzeit- und Zielbilder|Fotoprüfung und Zeitanpassung|So funktioniert die Zeitmessung|App-Screenshot mit Beispieldaten',
'starts':'Starte auf deine Art|Fünf Wege zum Start.|Wähle den passenden Zeitanker. Vergleiche Ergebnisse mit derselben Startmethode.|Fliegender Start|Beschleunige vor dem ersten Messpunkt. Die Startlinienüberquerung beginnt den Zeitabschnitt.|Touch Release|Halte den Bildschirm des Start-Handys. Beim Anheben des Fingers beginnt die Zeit.|Countdown|Ein Countdown endet mit einem Signal. Die Messung beginnt am Signal und schließt deine Reaktion ein.|Sprachkommando|Folge den gesprochenen Startkommandos. Bei GO beginnt die Zeit.|Start im Bild|Stehe an der Frontkamera-Linie des Start-Handys. Überquere die angezeigte Linie zum Start.',
'workflow':'Vom ersten Lauf zur nächsten Einheit|Dein Training an einem Ort.|Alle Funktionen entdecken|Zwischenzeiten & Durchschnittstempo|Miss den gesamten Lauf und seine Abschnitte. Sieh das Durchschnittstempo für deine Strecke.|Athleten & Teams|Ordne Läufe Athletenprofilen zu und halte Gruppeneinheiten übersichtlich.|Verlauf & Bestleistungen|Finde frühere Einheiten, vergleiche gleiche Tests und verfolge Fortschritte.|Vorlagen & Wiederholungen|Nutze eine Sprintvorlage oder eigene Distanz. Verwende gespeicherte Setups erneut.|CSV, Karten & Video|Exportiere Daten, teile Ergebniskarten oder erstelle Videos mit Zeiteinblendung.|Drahtlos & offline|Verbinde nahe Handys über unterstützte lokale Verbindungen. Speichere Ergebnisse und synchronisiere unterstützte Daten, sobald du online bist.',
'beta':'In Entwicklung|Das nächste Kapitel deines Trainings.|Apple-Watch-Starts und Laufdynamik. Solo-Sprints im Querformat. Fußball-Agility mit 5-10-5 und Pendelläufen.|Diese Funktionen werden physisch getestet und sind noch nicht in der öffentlichen App. Ein Veröffentlichungstermin ist nicht zugesagt.|Entwicklungsvorschau ansehen',
'founder':'Auf der Bahn entstanden|Von einem Athleten, der es selbst nutzt.|Sondre Guttormsen ist olympischer Stabhochspringer sowie Gründer und Entwickler von TrackSpeed. Sein Ziel: wiederholbare Sprinttests einfacher in den Trainingsalltag bringen.|Den Gründer kennenlernen|Sondre Guttormsen beim Stabhochsprung',
'faq':'Vor deinem ersten Lauf.|Reicht ein Handy?|Ja. Solo Laps erfasst wiederholte Überquerungen einer Kameralinie. Getrennte Start- und Zielpositionen nutzen verbundene Handys. Querformat-Sprints und Agility sind noch in Entwicklung.|Brauche ich Wi-Fi oder Internet?|Unterstützte lokale Verbindungen können ohne Internet messen. Wi-Fi Aware benötigt kompatible Hard- und Software; Bluetooth ist eine weitere Option. Cloud-Funktionen benötigen Internet.|Wie genau ist es?|Das hängt von Bildrate, Licht, Positionierung, Startmethode und Uhrensynchronisierung ab. Dezimalstellen garantieren keine Genauigkeit. Nutze ein stabiles Setup und prüfe die Fotos. TrackSpeed dient dem Training, nicht der offiziellen Wettkampfzeitmessung.|Funktioniert es mit Apple Watch oder Android?|Die hier beschriebene öffentliche App ist für iPhone und iPad. Watch, Querformat-Agility und Android werden entwickelt. Gleicher Funktionsumfang auf allen Plattformen ist nicht zugesagt.|Was kostet TrackSpeed?|Der Download ist kostenlos, In-App-Käufe sind verfügbar. Aktuelle Tarife, Preise, Testberechtigung und regionale Funktionen stehen in der App.',
'cta':'Für deine nächste Einheit|Linie setzen. Bestes geben.|Deine nächste Trainingseinheit ist ein guter Anfang.|iPhone & iPad · In-App-Käufe',
'footer':'Sprintzeitmessung für dein Training.|Mehr vom Entwickler|Watch und Querformat-Agility: in Entwicklung.'})

save('fr',{
'meta':'Le chrono sprint. Sur votre téléphone.|Chronométrage automatique, portes sans fil, tours solo, photos, profils et historique. Découvrez aussi les projets Watch et agilité.',
'nav':'Toutes les fonctions|Télécharger TrackSpeed|Fermer le menu|Découvrir|Guide des fonctions en anglais',
'hero':'Pour le travail entre les compétitions|Le chrono sprint.|Sur votre téléphone.|Transformez vos téléphones en système de chronométrage. Enregistrez départs, intermédiaires et arrivées. Suivez les progrès, course après course.|Choisir mon installation|iPhone et iPad · Téléchargement gratuit, achats intégrés|Créé par l’athlète olympique Sondre Guttormsen|TrackSpeed affiche un sprint lancé avec photos du départ et de l’arrivée|Dans TrackSpeed|Un temps que vous pouvez vérifier.|Sprint / Sprints lancés / Courses d’élan / Tests en équipe',
'facts':'téléphone pour les tours solo|téléphones pour les portes connectées|façons de démarrer un sprint',
'modes':'Votre séance. Votre installation.|Un chrono adapté à votre entraînement.|Entraînez-vous seul, connectez des portes ou découvrez nos développements.|Schéma du parcours, pas à l’échelle|Départ|Intermédiaire|Arrivée|Téléphone|Demi-tour|Centre|Ligne de tour|En développement|Disponible sur iOS|Montre',
'gates':'Portes connectées|Une séance. Chaque intermédiaire.|Placez un téléphone au départ et à l’arrivée. Ajoutez-en un pour mesurer les changements de vitesse par segment.|Mesurez le parcours et positionnez les téléphones.|Rejoignez la même séance et attendez que toutes les portes soient prêtes.|Courez. Vérifiez ensemble le temps et les photos.|2+ téléphones · Parcours mesuré · Supports stables',
'solo':'Tours solo|Vous. Un téléphone.|Placez une caméra près d’une ligne franchie plusieurs fois. Le premier passage démarre la séance ; les suivants enregistrent un tour et une photo.|Fixez le téléphone près d’une ligne bien visible.|Choisissez Solo Laps et vérifiez l’image.|Franchissez la même ligne à chaque tour ou retour.|1 téléphone · Passages répétés sur la même ligne',
'watch':'Apple Watch|La séance à votre poignet.|Nous développons les départs Watch, les résultats et la dynamique de course. L’iPhone jumelé relie la montre à la séance.|Jumelez la Watch à l’iPhone hôte de départ pour les départs Watch.|Utilisez d’autres téléphones à l’arrivée et aux intermédiaires.|Consultez le temps et les mesures de mouvement disponibles.|Aperçu en développement · Pas encore dans l’app publique',
'agility':'Agilité et sprints solo|Une caméra. Tout l’exercice.|Le mode paysage est en développement pour les départs arrêtés et lancés, le 5-10-5 et les allers-retours. Gardez tout le parcours visible.|Pour le 5-10-5, tracez trois lignes espacées de 5 yards.|Partez du centre, touchez les deux lignes extérieures, revenez au centre.|Le premier retour au centre est un intermédiaire. Vérifiez les deux touches en vidéo.|Aperçu en développement · Trépied et contrôle vidéo des touches',
'evidence':'Plus qu’un nombre|Voyez ce qui a arrêté le chrono.|Les passages caméra définissent le départ et l’arrivée. Ouvrez les photos, vérifiez la ligne et conservez le résultat avec la séance.|Détection automatique du passage|Images du départ, des intermédiaires et de l’arrivée|Vérification des photos et ajustement du temps|Comprendre le chronométrage|Capture de l’app avec données d’exemple',
'starts':'À vous de choisir le départ|Cinq façons de vous lancer.|Choisissez le repère adapté au test. Comparez des résultats avec la même méthode de départ.|Départ lancé|Accélérez avant la première porte. Le franchissement de la ligne démarre la zone chronométrée.|Relâchement tactile|Maintenez le doigt sur l’écran du téléphone de départ. Le lever déclenche le chrono.|Compte à rebours|Le compte à rebours se termine par un signal sonore. Le temps commence au signal et inclut votre réaction.|Commande vocale|Suivez les commandes de départ. Le chrono commence à GO.|Départ dans l’image|Placez-vous sur la ligne de la caméra avant du téléphone de départ. Franchissez-la pour démarrer.',
'workflow':'De la première répétition à la séance suivante|Votre entraînement, rassemblé.|Explorer toutes les fonctions|Intermédiaires et vitesse moyenne|Mesurez la course et ses segments. Consultez la vitesse moyenne sur la distance mesurée.|Athlètes et équipes|Attribuez les essais aux profils et organisez les séances en groupe.|Historique et records personnels|Retrouvez vos séances, comparez les mêmes tests et suivez vos progrès.|Modèles et séances répétées|Choisissez un modèle ou une distance personnalisée. Réutilisez une configuration.|CSV, cartes et vidéo|Exportez les données, partagez une carte ou créez une vidéo avec le chrono en surimpression.|Sans fil et hors ligne|Connectez les téléphones proches via les liaisons locales prises en charge. Enregistrez les résultats et synchronisez les données compatibles en ligne.',
'beta':'En développement|La suite de votre entraînement.|Départs Apple Watch et dynamique de course. Sprints solo en paysage. Agilité football avec 5-10-5 et allers-retours.|Ces fonctions sont testées sur le terrain et ne sont pas encore dans l’app publique. Aucune date de sortie n’est promise.|Voir l’aperçu en développement',
'founder':'Né sur la piste|Créé par un athlète qui l’utilise.|Sondre Guttormsen est perchiste olympique, fondateur et développeur de TrackSpeed. Son objectif : intégrer plus facilement des tests de sprint reproductibles à l’entraînement quotidien.|Rencontrer le fondateur|Sondre Guttormsen en compétition de saut à la perche',
'faq':'Avant votre première course.|Un seul téléphone suffit-il ?|Oui. Solo Laps mesure les passages répétés d’une même ligne. Des positions de départ et d’arrivée distinctes utilisent des téléphones connectés. Les sprints et l’agilité en paysage sont en développement.|Faut-il du Wi-Fi ou Internet ?|Les liaisons locales compatibles peuvent fonctionner sans Internet. Wi-Fi Aware exige du matériel et un logiciel compatibles ; Bluetooth est une autre option. Le cloud nécessite une connexion.|Quelle est la précision ?|Elle dépend de la fréquence d’image, de la lumière, du placement, du départ et de la synchronisation. Les décimales ne garantissent pas la précision. Stabilisez l’installation et vérifiez les photos. TrackSpeed sert à l’entraînement, pas au chronométrage officiel.|Apple Watch et Android sont-ils compatibles ?|L’expérience publique décrite ici concerne iPhone et iPad. Les fonctions Watch, l’agilité en paysage et Android sont en développement. La parité entre plateformes n’est pas promise.|Combien coûte TrackSpeed ?|L’app est gratuite à télécharger, avec achats intégrés. Consultez les offres, tarifs, conditions d’essai et fonctions disponibles dans votre région dans l’app.',
'cta':'Pour votre prochaine séance|Placez la ligne. Donnez le meilleur.|Votre prochain entraînement est un bon point de départ.|iPhone et iPad · Achats intégrés',
'footer':'Le chrono sprint au service de votre travail.|Du même développeur|Watch et agilité en paysage : en développement.'})

save('es',{
'meta':'Cronometraje de sprints. Con tu teléfono.|Cronometraje automático, puertas inalámbricas, vueltas en solitario, revisión de fotos, perfiles e historial. Descubre también los proyectos Watch y agilidad.',
'nav':'Todas las funciones|Descargar TrackSpeed|Cerrar menú|Explorar|Guía de funciones en inglés',
'hero':'Para el trabajo entre competiciones|Cronometra tu sprint.|Con tu teléfono.|Convierte los teléfonos que ya tienes en un sistema de cronometraje. Registra salidas, parciales y llegadas. Sigue tu progreso, carrera a carrera.|Elige tu configuración|iPhone y iPad · Descarga gratuita, compras en la app|Creado por el atleta olímpico Sondre Guttormsen|TrackSpeed muestra un sprint lanzado con fotos de salida y llegada|Dentro de TrackSpeed|Un tiempo que puedes volver a revisar.|Entrenamiento de sprint / Sprints lanzados / Carreras de aproximación / Pruebas de equipo',
'facts':'teléfono para vueltas en solitario|teléfonos para puertas conectadas|formas de iniciar un sprint',
'modes':'Tu sesión. Tu configuración.|Un cronometraje adaptado a tu entrenamiento.|Entrena solo, conecta varias puertas o descubre lo que estamos desarrollando.|Esquema ilustrativo del recorrido, sin escala|Salida|Parcial|Meta|Teléfono|Giro|Centro|Línea de vuelta|En desarrollo|Disponible en iOS|Reloj',
'gates':'Puertas conectadas|Una sesión. Todos los parciales.|Coloca teléfonos en la salida y la meta. Añade otro para medir cómo cambia tu velocidad por tramo.|Mide el recorrido y coloca los teléfonos.|Entra en la misma sesión y espera a que todas las puertas estén listas.|Corre y revisa juntos el tiempo y las fotos.|2+ teléfonos · Recorrido medido · Soportes estables',
'solo':'Vueltas en solitario|Solo tú. Un teléfono.|Coloca una cámara en una línea que cruces varias veces. El primer cruce inicia la sesión; los siguientes registran una vuelta y una foto.|Fija el teléfono junto a una línea bien marcada.|Elige Solo Laps y comprueba la imagen.|Cruza la misma línea en cada vuelta o regreso.|1 teléfono · Cruces repetidos de la misma línea',
'watch':'Apple Watch|Tu sesión en la muñeca.|Desarrollamos salidas desde el Watch, resultados y dinámica de carrera. El iPhone enlazado conecta el reloj con la sesión.|Para salidas desde el Watch, enlázalo al iPhone anfitrión de salida.|Usa otros teléfonos para la meta y los parciales.|Revisa el tiempo y las métricas de movimiento disponibles.|Versión en desarrollo · Aún no está en la app pública',
'agility':'Agilidad y sprints solo|Una cámara. Todo el ejercicio.|Desarrollamos el modo horizontal para salidas paradas y lanzadas, 5-10-5 e idas y vueltas. Mantén todo el recorrido visible.|Para el 5-10-5, marca tres líneas separadas por 5 yardas.|Sal del centro, toca ambas líneas exteriores y vuelve al centro.|El primer regreso por el centro es un parcial. Revisa ambos toques en vídeo.|Versión en desarrollo · Trípode y revisión de los giros en vídeo',
'evidence':'Más que un número|Mira qué detuvo el cronómetro.|Los cruces automáticos por cámara definen la salida y la llegada. Abre las fotos, comprueba la línea y guarda el resultado con la sesión.|Detección automática del cruce|Imágenes de salida, parciales y llegada|Revisión de fotos y ajuste del tiempo|Cómo funciona el cronometraje|Captura de la app con datos de ejemplo',
'starts':'Elige cómo salir|Cinco formas de empezar.|Elige el inicio que corresponda a tu prueba. Compara resultados con la misma modalidad de salida.|Salida lanzada|Acelera antes de la primera puerta. Cruzar la línea de salida inicia la zona cronometrada.|Soltar la pantalla|Mantén el dedo en la pantalla del teléfono de salida. Levantarlo inicia el tiempo.|Cuenta atrás|La cuenta atrás termina con una señal sonora. El tiempo empieza con la señal e incluye tu reacción.|Comando de voz|Sigue las órdenes habladas. El cronómetro empieza con GO.|Salida en imagen|Sitúate junto a la línea de la cámara frontal del teléfono de salida. Crúzala para empezar.',
'workflow':'De la primera repetición a la próxima sesión|Tu entrenamiento, organizado.|Explorar todas las funciones|Parciales y velocidad media|Mide la carrera y sus tramos. Consulta la velocidad media sobre la distancia medida.|Atletas y equipos|Asigna intentos a perfiles y organiza las sesiones de grupo.|Historial y mejores marcas|Encuentra sesiones anteriores, compara pruebas iguales y sigue el progreso.|Plantillas y sesiones repetidas|Usa una plantilla de sprint o una distancia propia. Reutiliza una configuración guardada.|CSV, tarjetas y vídeo|Exporta datos, comparte una tarjeta de resultado o crea un vídeo con el tiempo superpuesto.|Inalámbrico y sin conexión|Conecta teléfonos cercanos mediante conexiones locales compatibles. Guarda resultados y sincroniza los datos admitidos cuando tengas internet.',
'beta':'En desarrollo|El siguiente capítulo de tu entrenamiento.|Salidas con Apple Watch y dinámica de carrera. Sprints en solitario con el teléfono horizontal. Agilidad para fútbol, con 5-10-5 e idas y vueltas.|Estas funciones están en pruebas físicas y aún no forman parte de la app pública. No hay una fecha de lanzamiento prometida.|Ver las funciones en desarrollo',
'founder':'Nacido en la pista|Creado por un atleta que lo usa.|Sondre Guttormsen es pertiguista olímpico, fundador y desarrollador de TrackSpeed. Su objetivo: facilitar las pruebas de sprint repetibles en el entrenamiento diario.|Conoce al fundador|Sondre Guttormsen compitiendo en salto con pértiga',
'faq':'Antes de tu primera carrera.|¿Puedo usar un solo teléfono?|Sí. Solo Laps registra cruces repetidos de una misma línea. Para salida y meta separadas se conectan varios teléfonos. Los sprints y la agilidad con cámara horizontal están en desarrollo.|¿Necesito Wi-Fi o internet?|Las conexiones locales compatibles pueden cronometrar sin internet. Wi-Fi Aware requiere hardware y software compatibles; Bluetooth es otra opción. Las funciones en la nube necesitan conexión.|¿Qué precisión tiene?|Depende de los fotogramas por segundo, la luz, la colocación, la salida y la sincronización. Los decimales no garantizan precisión. Usa una instalación estable y revisa las fotos. TrackSpeed es para entrenar, no para el cronometraje oficial.|¿Funciona con Apple Watch o Android?|La experiencia pública descrita es para iPhone y iPad. Las funciones Watch, la agilidad horizontal y Android están en desarrollo. No se promete igualdad de funciones entre plataformas.|¿Cuánto cuesta TrackSpeed?|La descarga es gratuita, con compras en la app. Consulta allí los planes, precios, condiciones de prueba y funciones disponibles en tu región.',
'cta':'Para tu próxima sesión|Marca la línea. Da lo mejor.|Tu próximo entrenamiento es un buen momento para empezar.|iPhone y iPad · Compras en la app',
'footer':'Cronometraje de sprints para tu esfuerzo diario.|Más del desarrollador|Watch y agilidad horizontal: en desarrollo.'})

save('pt',{
'meta':'Cronometragem de sprints. No celular.|Cronometragem automática, pontos sem fio, voltas solo, fotos, perfis e histórico. Conheça também os projetos Watch e agilidade.',
'nav':'Todas as funções|Baixar TrackSpeed|Fechar menu|Explorar|Guia de funções em inglês',
'hero':'Para o trabalho entre competições|Cronometre seu sprint.|No seu celular.|Transforme os celulares que você já tem em um sistema de cronometragem. Registre largadas, parciais e chegadas. Acompanhe seu progresso, corrida após corrida.|Escolha sua configuração|iPhone e iPad · Download gratuito, compras no app|Criado pelo atleta olímpico Sondre Guttormsen|TrackSpeed exibe um sprint lançado com fotos da largada e da chegada|Dentro do TrackSpeed|Um tempo que você pode conferir depois.|Treino de sprint / Sprints lançados / Corridas de aproximação / Testes de equipe',
'facts':'celular para voltas solo|celulares para pontos conectados|formas de iniciar um sprint',
'modes':'Seu treino. Sua configuração.|Cronometragem que acompanha seu treino.|Treine sozinho, conecte pontos de cronometragem ou veja o que estamos desenvolvendo.|Esquema ilustrativo do percurso, sem escala|Largada|Parcial|Chegada|Celular|Retorno|Centro|Linha da volta|Em desenvolvimento|Disponível no iOS|Relógio',
'gates':'Pontos conectados|Um treino. Todas as parciais.|Posicione celulares na largada e na chegada. Adicione outro para acompanhar a velocidade em cada trecho.|Meça o percurso e posicione os celulares.|Entre na mesma sessão e aguarde todos os pontos ficarem prontos.|Corra e confira o tempo junto com as fotos.|2+ celulares · Percurso medido · Suportes estáveis',
'solo':'Voltas solo|Só você. Um celular.|Coloque a câmera em uma linha que você cruza repetidamente. A primeira passagem inicia a sessão; as próximas registram uma volta e uma foto.|Fixe o celular ao lado de uma linha bem marcada.|Escolha Solo Laps e confira a imagem da câmera.|Cruze a mesma linha a cada volta ou retorno.|1 celular · Passagens repetidas pela mesma linha',
'watch':'Apple Watch|Seu treino no pulso.|Estamos desenvolvendo largadas pelo Watch, resultados e dinâmica de corrida. O iPhone pareado conecta o relógio à sessão.|Para largadas pelo Watch, pareie com o iPhone anfitrião da largada.|Use outros celulares na chegada e nas parciais.|Confira o tempo e as métricas de movimento disponíveis.|Prévia em desenvolvimento · Ainda fora do app público',
'agility':'Agilidade e sprints solo|Uma câmera. O exercício inteiro.|O modo horizontal está em desenvolvimento para largadas paradas e lançadas, 5-10-5 e corridas de ida e volta. Mantenha o percurso visível.|Para o 5-10-5, marque três linhas separadas por 5 jardas.|Saia do centro, toque as duas linhas externas e retorne ao centro.|A primeira passagem de volta pelo centro é uma parcial. Confira os dois toques no vídeo.|Prévia em desenvolvimento · Tripé e revisão das viradas em vídeo',
'evidence':'Mais que um número|Veja o que parou o cronômetro.|As passagens automáticas pela câmera definem largada e chegada. Abra as fotos, confira a linha e guarde o resultado com a sessão.|Detecção automática de passagem|Imagens de largada, parciais e chegada|Revisão das fotos e ajuste do tempo|Como a cronometragem funciona|Captura do app com dados de exemplo',
'starts':'Escolha sua largada|Cinco formas de começar.|Escolha o início adequado ao teste. Compare resultados com o mesmo método de largada.|Largada lançada|Ganhe velocidade antes do primeiro ponto. Cruzar a linha de largada inicia o trecho cronometrado.|Soltar o toque|Mantenha o dedo na tela do celular de largada. Levantar o dedo inicia o tempo.|Contagem regressiva|A contagem termina com um sinal sonoro. O tempo começa no sinal e inclui sua reação.|Comando de voz|Siga os comandos falados. O cronômetro começa no GO.|Largada na imagem|Fique na linha da câmera frontal do celular de largada. Cruze a linha exibida para começar.',
'workflow':'Da primeira repetição ao próximo treino|Seu treino, organizado.|Explorar todas as funções|Parciais e velocidade média|Meça a corrida completa e seus trechos. Veja a velocidade média para a distância medida.|Atletas e equipes|Associe tentativas aos perfis e organize os treinos em grupo.|Histórico e recordes pessoais|Encontre sessões anteriores, compare testes iguais e acompanhe a evolução.|Modelos e sessões repetidas|Escolha um modelo de sprint ou uma distância própria. Reutilize uma configuração salva.|CSV, cartões e vídeo|Exporte dados, compartilhe um cartão de resultado ou crie um vídeo com o tempo sobreposto.|Sem fio e offline|Conecte celulares próximos usando conexões locais compatíveis. Salve resultados e sincronize os dados compatíveis quando estiver online.',
'beta':'Em desenvolvimento|O próximo capítulo do seu treino.|Largadas com Apple Watch e dinâmica de corrida. Sprints solo com celular horizontal. Agilidade para futebol, incluindo 5-10-5 e ida e volta.|Essas funções passam por testes físicos e ainda não estão no app público. Não há data de lançamento prometida.|Ver a prévia em desenvolvimento',
'founder':'Criado na pista|Feito por um atleta que usa o app.|Sondre Guttormsen é saltador com vara olímpico, fundador e desenvolvedor do TrackSpeed. Seu objetivo: facilitar testes de sprint repetíveis no treino diário.|Conheça o fundador|Sondre Guttormsen competindo no salto com vara',
'faq':'Antes da primeira corrida.|Posso usar apenas um celular?|Sim. Solo Laps registra passagens repetidas pela mesma linha. Largada e chegada em locais separados usam celulares conectados. Sprints e agilidade com câmera horizontal estão em desenvolvimento.|Preciso de Wi-Fi ou internet?|Conexões locais compatíveis podem cronometrar sem internet. Wi-Fi Aware exige hardware e software compatíveis; Bluetooth é outra opção. Funções na nuvem precisam de conexão.|Qual é a precisão?|Depende da taxa de quadros, luz, posição, largada e sincronização dos relógios. Casas decimais não garantem precisão. Use uma configuração estável e confira as fotos. TrackSpeed é para treino, não para cronometragem oficial.|Funciona com Apple Watch ou Android?|A experiência pública descrita aqui é para iPhone e iPad. Watch, agilidade horizontal e Android estão em desenvolvimento. Não prometemos os mesmos recursos em todas as plataformas.|Quanto custa o TrackSpeed?|O download é gratuito, com compras no app. Consulte no app os planos, preços, condições de teste e funções disponíveis na sua região.',
'cta':'Leve para o próximo treino|Marque a linha. Dê seu melhor.|Seu próximo treino é um bom lugar para começar.|iPhone e iPad · Compras no app',
'footer':'Cronometragem de sprints para o seu esforço diário.|Mais do desenvolvedor|Watch e agilidade horizontal: em desenvolvimento.'})

save('it',{
'meta':'Cronometra gli sprint. Con il telefono.|Cronometraggio automatico, porte wireless, giri in solitaria, foto, profili e cronologia. Scopri anche le anteprime Watch e agilità.',
'nav':'Tutte le funzioni|Scarica TrackSpeed|Chiudi menu|Esplora|Guida alle funzioni in inglese',
'hero':'Per il lavoro tra una gara e l’altra|Cronometra gli sprint.|Con il tuo telefono.|Trasforma i telefoni che hai già in un sistema di cronometraggio. Registra partenze, intermedi e arrivi. Segui i progressi, corsa dopo corsa.|Trova la configurazione|iPhone e iPad · Download gratuito, acquisti in-app|Creato dall’atleta olimpico Sondre Guttormsen|TrackSpeed mostra uno sprint lanciato con foto di partenza e arrivo|Dentro TrackSpeed|Un tempo che puoi ricontrollare.|Allenamento sprint / Sprint lanciati / Rincorse / Test di squadra',
'facts':'telefono per i giri in solitaria|telefoni per le porte collegate|modi per iniziare uno sprint',
'modes':'La tua sessione. Il tuo setup.|Un cronometro adatto al tuo allenamento.|Allenati da solo, collega le porte o scopri cosa stiamo sviluppando.|Schema illustrativo del percorso, non in scala|Partenza|Intermedio|Arrivo|Telefono|Inversione|Centro|Linea del giro|In sviluppo|Disponibile su iOS|Orologio',
'gates':'Porte collegate|Una sessione. Tutti gli intermedi.|Metti i telefoni alla partenza e all’arrivo. Aggiungine uno per misurare la velocità nei diversi tratti.|Misura il percorso e posiziona i telefoni.|Entra nella stessa sessione e attendi che tutte le porte siano pronte.|Corri e controlla insieme tempo e foto.|2+ telefoni · Percorso misurato · Supporti stabili',
'solo':'Giri in solitaria|Solo tu. Un telefono.|Posiziona una fotocamera su una linea che attraversi più volte. Il primo passaggio avvia la sessione; i successivi registrano un giro e una foto.|Fissa il telefono accanto a una linea ben segnata.|Scegli Solo Laps e controlla l’inquadratura.|Attraversa la stessa linea a ogni giro o ritorno.|1 telefono · Passaggi ripetuti sulla stessa linea',
'watch':'Apple Watch|La sessione al polso.|Stiamo sviluppando partenze Watch, risultati e dinamica di corsa. L’iPhone abbinato collega l’orologio alla sessione.|Per le partenze Watch, abbinalo all’iPhone host di partenza.|Usa altri telefoni per arrivo e intermedi.|Controlla il tempo e le metriche di movimento disponibili.|Anteprima in sviluppo · Non ancora nell’app pubblica',
'agility':'Agilità e sprint solo|Una fotocamera. Tutto l’esercizio.|Il cronometraggio orizzontale è in sviluppo per partenze da fermo e lanciate, 5-10-5 e navette. Mantieni visibile tutto il percorso.|Per il 5-10-5, segna tre linee distanti 5 yard.|Parti dal centro, tocca le due linee esterne e torna al centro.|Il primo ritorno attraverso il centro è un intermedio. Controlla entrambi i tocchi nel video.|Anteprima in sviluppo · Treppiede e controllo video delle inversioni',
'evidence':'Più di un numero|Guarda cosa ha fermato il tempo.|I passaggi automatici della fotocamera definiscono partenza e arrivo. Apri le foto, controlla la linea e conserva il risultato nella sessione.|Rilevamento automatico del passaggio|Immagini di partenza, intermedi e arrivo|Controllo delle foto e regolazione del tempo|Come funziona il cronometraggio|Schermata dell’app con dati di esempio',
'starts':'Scegli come partire|Cinque modi per iniziare.|Scegli l’inizio adatto al test. Confronta risultati con lo stesso metodo di partenza.|Partenza lanciata|Accelera prima della prima porta. Attraversare la linea di partenza avvia il tratto cronometrato.|Rilascio del tocco|Tieni il dito sullo schermo del telefono di partenza. Sollevarlo avvia il tempo.|Conto alla rovescia|Il conto termina con un segnale acustico. Il tempo inizia al segnale e include la tua reazione.|Comando vocale|Segui i comandi di partenza. Il cronometro parte al GO.|Partenza nell’inquadratura|Posizionati sulla linea della fotocamera frontale del telefono di partenza. Attraversala per iniziare.',
'workflow':'Dalla prima ripetuta alla prossima sessione|Il tuo allenamento, organizzato.|Esplora tutte le funzioni|Intermedi e velocità media|Misura la corsa completa e i segmenti. Consulta la velocità media sulla distanza misurata.|Atleti e squadre|Assegna le prove ai profili e organizza le sessioni di gruppo.|Cronologia e record personali|Ritrova le sessioni, confronta test uguali e segui i progressi.|Modelli e sessioni ripetute|Scegli un modello di sprint o una distanza personale. Riutilizza un setup salvato.|CSV, schede e video|Esporta dati, condividi una scheda risultato o crea video con il tempo in sovrimpressione.|Wireless e offline|Collega i telefoni vicini con connessioni locali supportate. Salva i risultati e sincronizza i dati compatibili quando sei online.',
'beta':'In sviluppo|Il prossimo capitolo del tuo allenamento.|Partenze Apple Watch e dinamica di corsa. Sprint solo con telefono orizzontale. Agilità per il calcio, con 5-10-5 e navette.|Queste funzioni sono in fase di test sul campo e non sono ancora nell’app pubblica. Non è promessa una data di uscita.|Scopri l’anteprima in sviluppo',
'founder':'Nato in pista|Creato da un atleta che lo usa.|Sondre Guttormsen è un astista olimpico, fondatore e sviluppatore di TrackSpeed. L’obiettivo: rendere più semplici i test di sprint ripetibili nell’allenamento quotidiano.|Conosci il fondatore|Sondre Guttormsen in gara nel salto con l’asta',
'faq':'Prima della prima corsa.|Basta un telefono?|Sì. Solo Laps registra passaggi ripetuti sulla stessa linea. Partenza e arrivo separati richiedono telefoni collegati. Sprint e agilità con fotocamera orizzontale sono in sviluppo.|Servono Wi-Fi o internet?|Le connessioni locali compatibili possono cronometrare senza internet. Wi-Fi Aware richiede hardware e software compatibili; Bluetooth è un’altra opzione. Il cloud richiede una connessione.|Quanto è preciso?|Dipende da frequenza dei fotogrammi, luce, posizione, partenza e sincronizzazione. Le cifre decimali non garantiscono precisione. Usa un setup stabile e controlla le foto. TrackSpeed è per l’allenamento, non per il cronometraggio ufficiale.|Funziona con Apple Watch o Android?|L’esperienza pubblica descritta è per iPhone e iPad. Watch, agilità orizzontale e Android sono in sviluppo. Non promettiamo funzioni identiche su tutte le piattaforme.|Quanto costa TrackSpeed?|Il download è gratuito, con acquisti in-app. Consulta nell’app piani, prezzi, condizioni di prova e funzioni disponibili nella tua regione.',
'cta':'Portalo al prossimo allenamento|Segna la linea. Dai il massimo.|La prossima sessione è un buon punto di partenza.|iPhone e iPad · Acquisti in-app',
'footer':'Cronometraggio sprint per il tuo impegno quotidiano.|Altro dallo sviluppatore|Watch e agilità orizzontale: in sviluppo.'})

save('ja',{
'meta':'スマホで、スプリント計測。|自動タイム計測、ワイヤレスゲート、ソロラップ、写真確認、選手プロフィール、セッション履歴。Watchとアジリティの開発プレビューも紹介。',
'nav':'すべての機能|TrackSpeedを入手|メニューを閉じる|詳しく見る|機能ガイドは英語です',
'hero':'試合と試合の間のトレーニングに|スプリント計測。|そのスマホで。|今あるスマホをタイム計測システムに。スタート、区間、フィニッシュを記録し、一本ずつ成長を振り返れます。|自分に合う設定を探す|iPhone・iPad対応 · 無料ダウンロード、アプリ内課金あり|オリンピアンのSondre Guttormsenが開発|フライングスプリントのスタートとフィニッシュ写真を表示したTrackSpeed|TrackSpeedの画面|後から確かめられるタイム。|スプリント練習 / フライングスプリント / 助走 / チーム測定',
'facts':'台でソロラップ|台以上でゲートを接続|種類のスタート方法',
'modes':'練習に合わせて、設定を選ぶ。|あなたの練習に合う計測を。|一人で練習する、複数のゲートをつなぐ、開発中の機能を知る。|コースの模式図です。実際の縮尺とは異なります|スタート|区間|フィニッシュ|スマホ|折り返し|中央|ラップライン|開発中|iOSで利用可能|Watch',
'gates':'接続ゲート|一つの練習。すべての区間。|スタートとフィニッシュにスマホを設置。区間用にもう一台追加すれば、区間ごとの速度を確認できます。|距離を測り、各スマホを設置します。|同じセッションに参加し、すべてのゲートが準備完了になるまで待ちます。|走った後、タイムと通過写真を一緒に確認します。|スマホ2台以上 · 実測したコース · 安定した固定具',
'solo':'ソロラップ|あなたと、スマホ一台。|繰り返し通過するラインにカメラを設置。最初の通過で開始し、その後の通過ごとにラップと写真を記録します。|明確に示したラインの横にスマホを固定します。|Solo Lapsを選び、カメラの映像を確認します。|各周回や戻りで同じラインを通過します。|スマホ1台 · 同じラインを繰り返し通過',
'watch':'Apple Watch|手首でセッションを確認。|Watchからのスタート、結果表示、ランニングダイナミクスを開発中です。ペアリングしたiPhoneがWatchと計測セッションをつなぎます。|Watchスタートでは、ホスト兼スタート用iPhoneとペアリングします。|フィニッシュや区間には別のスマホを使います。|タイムと利用可能な動作データを確認します。|開発プレビュー · 公開アプリには未搭載',
'agility':'アジリティ・ソロスプリント|一台のカメラで、ドリル全体を。|横向きの計測を、静止・フライングスタート、5-10-5、往復走向けに開発中。実測したコース全体を画面に収めます。|5-10-5では、5ヤード間隔で3本のラインを引きます。|中央から出て両端のラインに触れ、中央に戻ります。|最初に中央を戻り通過する時点は区間タイムです。両端のタッチは動画で確認します。|開発プレビュー · 三脚と折り返しの動画確認が必要',
'evidence':'数字だけで終わらない|時計が止まった瞬間を確認。|カメラの自動通過検出でスタートとフィニッシュを記録。写真を開き、ラインを確認し、結果をセッションと一緒に保存できます。|自動通過検出|スタート・区間・フィニッシュの記録画像|写真の確認とタイム調整|計測の仕組み|サンプルデータを使用したアプリ画面',
'starts':'スタート方法を選ぶ|始め方は、5通り。|テストに合う開始点を選びましょう。同じスタート方法の結果同士を比較してください。|フライングスタート|最初のゲート前で加速。スタートラインの通過で計測区間が始まります。|タッチリリース|スタート用スマホの画面を指で押さえ、指を離すと計測が始まります。|カウントダウン|カウントダウン後の音を合図に開始。タイムには合図への反応時間も含まれます。|音声コマンド|音声のスタート指示に従います。GOで計測が始まります。|画面内スタート|スタート用スマホの前面カメラのラインに立ち、画面上のラインを通過して開始します。',
'workflow':'最初の一本から、次の練習まで|トレーニングを、一か所に。|すべての機能を見る|区間タイムと平均速度|全体と各区間を計測し、実測した距離での平均速度を確認。|選手とチーム|走行結果を選手プロフィールに割り当て、グループ練習を整理。|履歴と自己ベスト|過去のセッションを探し、同じテストを比較して進歩を確認。|テンプレートと繰り返し練習|スプリント用テンプレートや任意の距離を選択。保存した設定を再利用。|CSV・カード・動画|データを出力し、結果カードを共有したり、タイム表示付き動画を作成。|ワイヤレス・オフライン計測|対応するローカル接続で近くのスマホを連携。結果を保存し、オンライン時に対応データを同期。',
'beta':'開発中|トレーニングの、次の一歩。|Apple Watchからのスタートとランニングダイナミクス。横向きスマホでのソロスプリント。5-10-5や往復走など、サッカー向けのアジリティテスト。|これらの機能は実機・実走テスト中で、公開アプリには未搭載です。公開日は未定です。|開発プレビューを見る',
'founder':'トラックから生まれた|自ら使う選手が、開発。|Sondre Guttormsenはオリンピック棒高跳び選手で、TrackSpeedの創設者・開発者です。日々の練習で再現性のあるスプリント測定を、もっと使いやすくすることが目標です。|創設者について|棒高跳びで競技中のSondre Guttormsen',
'faq':'最初の一本の前に。|スマホ一台で使えますか？|はい。Solo Lapsは同じカメラのラインの繰り返し通過を記録します。離れたスタートとフィニッシュには複数のスマホを使います。横向き一台でのスプリントとアジリティは開発中です。|Wi-Fiやインターネットは必要ですか？|対応するローカル接続ならインターネットなしで計測できます。Wi-Fi Awareには対応ハードウェアとソフトウェアが必要で、Bluetoothも選べます。クラウド機能には通信が必要です。|精度はどのくらいですか？|フレームレート、明るさ、設置、開始方法、時計同期に左右されます。小数桁の多さは精度の保証ではありません。安定した設置と通過写真の確認を行ってください。公式競技計測ではなく、練習用です。|Apple WatchやAndroidに対応していますか？|このサイトで紹介する公開版はiPhone・iPad用です。Watch、横向きアジリティ、Androidは開発中で、全プラットフォームの同一機能を約束するものではありません。|料金はいくらですか？|無料ダウンロードとアプリ内課金があります。地域に応じたプラン、価格、体験条件、機能はアプリ内で確認してください。',
'cta':'次の練習に持っていこう|ラインを決めて、全力で。|次のトレーニングから始めてみましょう。|iPhone・iPad · アプリ内課金あり',
'footer':'日々の努力を記録するスプリント計測。|同じ開発者のアプリ|Watch・横向きアジリティ：開発中。'})

save('zh-Hans',{
'meta':'用手机，为冲刺计时。|自动冲刺计时、无线计时门、单人圈速、照片复核、运动员档案与训练历史。了解Watch与敏捷训练开发预览。',
'nav':'全部功能|下载TrackSpeed|关闭菜单|探索|功能指南目前为英文',
'hero':'为比赛之间的每一次训练|冲刺计时。|用你的手机。|把已有的手机变成计时系统。记录起跑、分段和终点，一次次回顾训练进步。|选择你的设置|适用于iPhone和iPad · 免费下载，含App内购买|由奥运选手Sondre Guttormsen开发|TrackSpeed显示行进间冲刺的起点和终点照片|TrackSpeed应用画面|一个可以回头核对的成绩。|冲刺训练 / 行进间冲刺 / 助跑 / 团队测试',
'facts':'部手机测单人圈速|部及以上手机连接计时门|种冲刺起跑方式',
'modes':'你的训练。你的设置。|适合你训练方式的计时。|独自训练、连接多个计时门，或了解正在开发的新功能。|路线示意图，不按比例绘制|起点|分段|终点|手机|折返|中点|圈速线|开发中|iOS已提供|手表',
'gates':'互联计时门|一次训练，记录每个分段。|在起点和终点放置手机，再增加一部测分段，了解各段的速度变化。|测量路线并固定每部手机。|加入同一训练，等待所有计时门就绪。|跑完后，一起查看成绩和过线照片。|2部及以上手机 · 已测量路线 · 稳定支架',
'solo':'单人圈速|只有你，一部手机。|把相机放在会反复经过的线上。首次过线开始计时，之后每次记录一圈和一张照片。|将手机固定在清晰标记的线旁。|选择Solo Laps，检查相机画面。|每圈或每次返回时通过同一条线。|1部手机 · 反复通过同一条线',
'watch':'Apple Watch|在手腕上掌握训练。|正在开发Watch起跑、成绩显示和跑步动态。已配对的iPhone把手表连接到计时训练。|使用Watch起跑时，将其与主机/起跑iPhone配对。|其他手机负责终点和可选的分段。|查看成绩及可用的运动指标。|开发预览 · 尚未包含在公开版App中',
'agility':'敏捷与单人冲刺|一部相机，覆盖整个练习。|横屏计时正在开发，支持静止与行进间起跑、5-10-5及往返跑。测量后的整条路线需在画面内。|5-10-5需要标出三条线，相邻间距5码。|从中点出发，触碰两侧外线，再回到中点。|第一次返回并穿过中点记录分段。两次外线触碰都需通过视频复核。|开发预览 · 需三脚架与折返视频复核',
'evidence':'不只是一个数字|看看是什么停下了计时。|相机自动过线检测记录起点和终点。打开照片，核对计时线，并把成绩保存在训练中。|自动过线检测|起点、分段与终点图像|照片复核与时间调整|了解计时原理|使用示例训练数据的App截图',
'starts':'选择你的起跑方式|五种方式，开始冲刺。|选择符合测试目的的计时起点。请比较使用相同起跑方式的成绩。|行进间起跑|在第一个计时门前加速，通过起点线后开始测量区间。|松手起跑|按住起跑手机的屏幕，抬起手指即开始计时。|倒计时|倒计时结束后发出声音信号。计时从信号开始，包含你的反应时间。|语音指令|跟随语音起跑指令，计时从GO开始。|画面内起跑|站在起跑手机前置相机的计时线旁，通过画面中的线开始计时。',
'workflow':'从第一组，到下一次训练|把训练记录放在一起。|探索全部功能|分段与平均速度|测量全程和各分段，查看实测距离上的平均速度。|运动员与团队|将每次成绩分配给运动员档案，有序管理团队训练。|历史与个人最佳|查找过往训练，比较相同测试，跟踪长期进步。|模板与重复训练|选择冲刺模板或自定义距离，重复使用已保存的设置。|CSV、卡片与视频|导出数据、分享成绩卡片，或生成带计时叠加层的视频。|无线与离线计时|通过支持的本地连接联结附近手机。保存成绩，联网后同步受支持的数据。',
'beta':'开发中|训练的下一篇章。|Apple Watch起跑与跑步动态。横屏单人冲刺。面向足球的敏捷测试，包括5-10-5和往返跑。|这些功能正在进行实地测试，尚未包含在公开版App中。目前不承诺发布日期。|查看开发预览',
'founder':'诞生于田径场|由亲自使用它的运动员打造。|Sondre Guttormsen是奥运撑杆跳高选手，也是TrackSpeed的创始人与开发者。目标很实际：让可重复的冲刺测试更容易融入日常训练。|了解创始人|Sondre Guttormsen参加撑杆跳高比赛',
'faq':'第一次跑之前。|只用一部手机可以吗？|可以。Solo Laps记录反复通过同一相机计时线的过程。起点与终点分开时需要连接多部手机。单相机横屏冲刺与敏捷模式仍在开发中。|需要Wi-Fi或互联网吗？|受支持的本地连接可在没有互联网时计时。Wi-Fi Aware需要兼容的硬件与软件；Bluetooth也是一种连接选项。云端功能需要网络。|准确度如何？|结果取决于帧率、光线、摆放、起跑方式与时钟同步。小数位数不等于准确度保证。请保持稳定设置并复核过线照片。TrackSpeed用于训练，不用于官方比赛计时。|支持Apple Watch或Android吗？|此处介绍的公开版适用于iPhone与iPad。Watch功能、横屏敏捷及Android都在开发中，不承诺各平台功能完全一致。|TrackSpeed多少钱？|App可免费下载，含App内购买。请在App中查看你所在地区的套餐、价格、试用资格及可用功能。',
'cta':'带到下一次训练|设好计时线，全力跑。|从下一次训练开始吧。|iPhone与iPad · 含App内购买',
'footer':'为每一天的努力记录冲刺成绩。|开发者的更多应用|Watch与横屏敏捷：开发中。'})

save('ko',{
'meta':'스프린트 기록. 내 휴대폰으로.|자동 스프린트 측정, 무선 게이트, 솔로 랩, 사진 검토, 선수 프로필과 세션 기록. Watch와 민첩성 기능 개발 소식도 확인하세요.',
'nav':'전체 기능|TrackSpeed 다운로드|메뉴 닫기|둘러보기|기능 가이드는 영어로 제공됩니다',
'hero':'대회 사이, 매일의 훈련을 위해|스프린트 기록.|내 휴대폰으로.|이미 가진 휴대폰을 기록 측정 시스템으로 바꾸세요. 출발, 구간, 도착을 기록하고 한 번의 질주마다 발전을 확인하세요.|내게 맞는 설정|iPhone 및 iPad · 무료 다운로드, 앱 내 구입|올림픽 선수 Sondre Guttormsen이 개발|플라잉 스프린트의 출발과 도착 사진을 표시한 TrackSpeed|TrackSpeed 화면|다시 확인할 수 있는 기록.|스프린트 훈련 / 플라잉 스프린트 / 도움닫기 / 팀 테스트',
'facts':'대로 솔로 랩 측정|대 이상으로 게이트 연결|가지 스프린트 출발 방식',
'modes':'내 훈련에 맞게 설정하세요.|훈련에 맞는 기록 측정.|혼자 훈련하고, 게이트를 연결하고, 개발 중인 기능을 살펴보세요.|실제 축척과 다른 코스 개념도|출발|구간|도착|휴대폰|반환|중앙|랩 라인|개발 중|iOS에서 이용 가능|워치',
'gates':'연결 게이트|한 세션의 모든 구간.|출발과 도착 지점에 휴대폰을 놓으세요. 구간용 한 대를 추가하면 구간별 속도 변화를 확인할 수 있습니다.|거리를 측정하고 휴대폰을 고정합니다.|같은 세션에 참여하고 모든 게이트가 준비될 때까지 기다립니다.|달린 뒤 기록과 통과 사진을 함께 확인합니다.|휴대폰 2대 이상 · 측정한 코스 · 안정적인 거치대',
'solo':'솔로 랩|나와 휴대폰 한 대.|반복해서 지나는 라인에 카메라를 설치하세요. 첫 통과로 시작하고 이후 통과마다 랩과 사진을 기록합니다.|명확하게 표시한 라인 옆에 휴대폰을 고정합니다.|Solo Laps를 선택하고 카메라 화면을 확인합니다.|매 바퀴나 복귀 때 같은 라인을 통과합니다.|휴대폰 1대 · 같은 라인 반복 통과',
'watch':'Apple Watch|손목에서 세션을 확인하세요.|Watch 출발, 결과 표시와 러닝 다이내믹스를 개발 중입니다. 페어링된 iPhone이 워치를 기록 세션에 연결합니다.|Watch 출발은 호스트/출발 iPhone과 페어링합니다.|다른 휴대폰은 도착과 선택한 구간에 배치합니다.|시간과 이용 가능한 동작 지표를 확인합니다.|개발 미리보기 · 공개 앱에는 아직 미포함',
'agility':'민첩성 및 솔로 스프린트|카메라 하나로 드릴 전체를.|정지·플라잉 출발, 5-10-5 및 왕복 달리기를 위한 가로 모드 측정을 개발 중입니다. 측정한 코스 전체가 보여야 합니다.|5-10-5는 5야드 간격으로 세 라인을 표시합니다.|중앙에서 출발해 양 끝 라인을 터치하고 중앙으로 돌아옵니다.|처음 중앙으로 돌아오는 통과는 구간 기록입니다. 양 끝 터치는 영상으로 확인합니다.|개발 미리보기 · 삼각대와 반환 동작 영상 검토 필요',
'evidence':'숫자 그 이상|시간이 멈춘 순간을 보세요.|자동 카메라 통과 감지로 출발과 도착을 기록합니다. 사진을 열어 라인을 확인하고 결과를 세션에 저장하세요.|자동 라인 통과 감지|출발·구간·도착 이미지|사진 검토와 시간 조정|측정 방식 알아보기|예시 세션 데이터를 사용한 앱 화면',
'starts':'출발 방식을 선택하세요|다섯 가지 시작 방식.|테스트에 맞는 시작 기준을 고르세요. 같은 출발 방식으로 측정한 결과를 비교하세요.|플라잉 출발|첫 게이트 앞에서 가속합니다. 출발 라인을 통과하면 측정 구간이 시작됩니다.|터치 릴리스|출발 휴대폰 화면을 누르고 있다가 손가락을 떼면 측정이 시작됩니다.|카운트다운|카운트다운 뒤 소리 신호가 나옵니다. 신호부터 시간이 시작되므로 반응 시간도 포함됩니다.|음성 명령|음성 출발 지시를 따르세요. GO에서 측정이 시작됩니다.|화면 내 출발|출발 휴대폰 전면 카메라의 라인에 서서 화면에 표시된 라인을 통과하면 시작됩니다.',
'workflow':'첫 반복부터 다음 세션까지|훈련 기록을 한곳에.|전체 기능 살펴보기|구간 및 평균 속도|전체와 구간 시간을 측정하고 실측 거리에 대한 평균 속도를 확인하세요.|선수와 팀|결과를 선수 프로필에 배정하고 그룹 훈련을 정리하세요.|기록 및 개인 최고|지난 세션을 찾아 같은 테스트끼리 비교하고 발전을 확인하세요.|템플릿과 반복 세션|스프린트 템플릿이나 직접 정한 거리를 사용하고 저장한 설정을 재사용하세요.|CSV, 카드 및 영상|데이터를 내보내고 기록 카드를 공유하거나 시간 오버레이 영상을 만드세요.|무선 및 오프라인 측정|지원되는 로컬 연결로 가까운 휴대폰을 연결합니다. 결과를 저장하고 온라인에서 지원 데이터를 동기화하세요.',
'beta':'개발 중|훈련의 다음 장.|Apple Watch 출발과 러닝 다이내믹스. 가로 모드 솔로 스프린트. 5-10-5와 왕복 달리기 등 축구 민첩성 테스트.|실제 기기와 현장에서 시험 중인 기능이며 아직 공개 앱에 포함되지 않았습니다. 출시일은 정해지지 않았습니다.|개발 미리보기 확인',
'founder':'트랙에서 시작했습니다|직접 사용하는 선수가 만들었습니다.|Sondre Guttormsen은 올림픽 장대높이뛰기 선수이자 TrackSpeed의 창립자 겸 개발자입니다. 매일의 훈련에서 반복 가능한 스프린트 테스트를 더 쉽게 만드는 것이 목표입니다.|창립자 소개|장대높이뛰기에 출전한 Sondre Guttormsen',
'faq':'첫 질주 전에.|휴대폰 한 대만 써도 되나요?|네. Solo Laps는 같은 카메라 라인의 반복 통과를 기록합니다. 떨어진 출발과 도착 지점은 연결한 휴대폰들을 사용합니다. 가로 모드 한 카메라 스프린트와 민첩성은 개발 중입니다.|Wi-Fi나 인터넷이 필요한가요?|지원되는 로컬 연결은 인터넷 없이도 측정할 수 있습니다. Wi-Fi Aware는 호환 하드웨어와 소프트웨어가 필요하며 Bluetooth도 선택할 수 있습니다. 클라우드 기능에는 인터넷이 필요합니다.|얼마나 정확한가요?|프레임 속도, 조명, 배치, 출발 방식과 시계 동기화에 영향을 받습니다. 소수점 자릿수가 정확도를 보장하지는 않습니다. 안정적으로 설치하고 통과 사진을 검토하세요. 공식 대회가 아닌 훈련용 측정입니다.|Apple Watch나 Android를 지원하나요?|이 사이트에서 소개하는 공개 앱은 iPhone과 iPad용입니다. Watch, 가로 민첩성 및 Android는 개발 중이며 모든 플랫폼에서 동일한 기능을 보장하지 않습니다.|TrackSpeed 요금은 얼마인가요?|무료 다운로드와 앱 내 구입을 제공합니다. 해당 지역의 요금제, 가격, 체험 조건 및 기능은 앱에서 확인하세요.',
'cta':'다음 훈련에 가져가세요|라인을 정하고, 최선을 다하세요.|다음 훈련부터 시작해 보세요.|iPhone 및 iPad · 앱 내 구입',
'footer':'매일의 노력을 위한 스프린트 측정.|개발자의 다른 앱|Watch와 가로 민첩성: 개발 중.'})

save('hi',{
'meta':'स्प्रिंट टाइमिंग। आपके फ़ोन से।|अपने आप स्प्रिंट टाइमिंग, वायरलेस गेट, सोलो लैप, फ़ोटो समीक्षा, खिलाड़ी प्रोफ़ाइल और सत्र इतिहास। Watch और चपलता प्रशिक्षण का विकास पूर्वावलोकन भी देखें।',
'nav':'सभी सुविधाएँ|TrackSpeed डाउनलोड करें|मेन्यू बंद करें|देखें|सुविधा गाइड अंग्रेज़ी में है',
'hero':'मुकाबलों के बीच की मेहनत के लिए|स्प्रिंट टाइमिंग।|आपके फ़ोन से।|अपने मौजूदा फ़ोन को टाइमिंग सिस्टम बनाएँ। शुरुआत, स्प्लिट और फ़िनिश रिकॉर्ड करें। हर दौड़ के साथ अपनी प्रगति देखें।|अपना सेटअप चुनें|iPhone और iPad · मुफ़्त डाउनलोड, ऐप में खरीदारी|ओलंपियन Sondre Guttormsen द्वारा विकसित|TrackSpeed में फ्लाइंग स्प्रिंट की शुरुआत और फ़िनिश की फ़ोटो|TrackSpeed की एक झलक|एक समय जिसे दोबारा जाँच सकते हैं।|स्प्रिंट प्रशिक्षण / फ्लाइंग स्प्रिंट / रन-अप / टीम टेस्ट',
'facts':'फ़ोन से सोलो लैप|फ़ोन से जुड़े टाइमिंग गेट|तरह से स्प्रिंट शुरू करें',
'modes':'आपका सत्र। आपका सेटअप।|आपके प्रशिक्षण के अनुसार टाइमिंग।|अकेले प्रशिक्षण लें, कई गेट जोड़ें या विकास में मौजूद सुविधाएँ देखें।|मार्ग का उदाहरण, वास्तविक पैमाने पर नहीं|शुरुआत|स्प्लिट|फ़िनिश|फ़ोन|मोड़|बीच|लैप लाइन|विकास में|iOS पर उपलब्ध|घड़ी',
'gates':'जुड़े हुए गेट|एक सत्र। हर स्प्लिट।|शुरुआत और फ़िनिश पर फ़ोन रखें। बीच में एक और फ़ोन जोड़कर अलग-अलग हिस्सों की गति देखें।|मार्ग की दूरी मापें और फ़ोन स्थिर रखें।|एक ही सत्र में जुड़ें और सभी गेट तैयार होने तक प्रतीक्षा करें।|दौड़ें, फिर समय और लाइन पार करने की फ़ोटो साथ देखें।|2+ फ़ोन · मापा हुआ मार्ग · स्थिर स्टैंड',
'solo':'सोलो लैप|सिर्फ़ आप। एक फ़ोन।|कैमरा उस लाइन पर रखें जिसे आप बार-बार पार करते हैं। पहली बार पार करने से सत्र शुरू होता है; अगली बार लैप और फ़ोटो रिकॉर्ड होती है।|साफ़ चिह्नित लाइन के पास फ़ोन स्थिर करें।|Solo Laps चुनें और कैमरे का दृश्य जाँचें।|हर चक्कर या वापसी पर उसी लाइन को पार करें।|1 फ़ोन · एक ही लाइन बार-बार पार करना',
'watch':'Apple Watch|सत्र की जानकारी आपकी कलाई पर।|Watch से शुरुआत, परिणाम और रनिंग डायनेमिक्स विकास में हैं। पेयर किया गया iPhone घड़ी को टाइमिंग सत्र से जोड़ता है।|Watch से शुरुआत के लिए उसे होस्ट/स्टार्ट iPhone से पेयर करें।|फ़िनिश और वैकल्पिक स्प्लिट के लिए दूसरे फ़ोन रखें।|समय और उपलब्ध मूवमेंट आँकड़े देखें।|विकास पूर्वावलोकन · सार्वजनिक ऐप में अभी नहीं',
'agility':'चपलता और सोलो स्प्रिंट|एक कैमरा। पूरी ड्रिल।|आड़े फ़ोन से खड़े और फ्लाइंग स्टार्ट, 5-10-5 तथा आगे-पीछे दौड़ की टाइमिंग विकास में है। पूरा मापा मार्ग कैमरे में रखें।|5-10-5 के लिए 5 यार्ड की दूरी पर तीन लाइनें बनाएँ।|बीच से शुरू करें, दोनों बाहरी लाइनों को छुएँ और बीच में लौटें।|पहली बार बीच से वापस गुजरना स्प्लिट है। दोनों छूने की क्रियाएँ वीडियो में जाँचें।|विकास पूर्वावलोकन · ट्राइपॉड और मोड़ की वीडियो समीक्षा',
'evidence':'सिर्फ़ एक संख्या से आगे|देखें, घड़ी कहाँ रुकी।|कैमरे से अपने आप लाइन पार करने की पहचान शुरुआत और फ़िनिश दर्ज करती है। फ़ोटो खोलें, लाइन जाँचें और परिणाम सत्र में रखें।|लाइन पार करने की स्वतः पहचान|शुरुआत, स्प्लिट और फ़िनिश की तस्वीरें|फ़ोटो समीक्षा और समय समायोजन|टाइमिंग कैसे काम करती है|उदाहरण डेटा वाला ऐप स्क्रीनशॉट',
'starts':'अपनी शुरुआत चुनें|शुरू करने के पाँच तरीके।|अपने टेस्ट के अनुसार समय शुरू करने का तरीका चुनें। एक ही शुरुआत वाले परिणामों की तुलना करें।|फ्लाइंग स्टार्ट|पहले गेट से पहले गति बढ़ाएँ। स्टार्ट लाइन पार करने पर मापा हिस्सा शुरू होता है।|टच रिलीज़|स्टार्ट फ़ोन की स्क्रीन पर उँगली रखें। उँगली हटाते ही टाइमर शुरू होता है।|उलटी गिनती|गिनती के बाद आवाज़ का संकेत मिलता है। समय संकेत से शुरू होता है और प्रतिक्रिया समय शामिल करता है।|आवाज़ का निर्देश|बोले गए स्टार्ट निर्देशों का पालन करें। GO पर टाइमर शुरू होता है।|फ़्रेम में शुरुआत|स्टार्ट फ़ोन के सामने वाले कैमरे की लाइन पर खड़े हों। स्क्रीन की लाइन पार करके शुरुआत करें।',
'workflow':'पहली रिपीट से अगले सत्र तक|आपका प्रशिक्षण, एक जगह।|हर सुविधा देखें|स्प्लिट और औसत गति|पूरी दौड़ और उसके हिस्सों का समय मापें। मापी गई दूरी की औसत गति देखें।|खिलाड़ी और टीम|दौड़ को खिलाड़ी प्रोफ़ाइल से जोड़ें और समूह सत्र व्यवस्थित रखें।|इतिहास और व्यक्तिगत सर्वश्रेष्ठ|पिछले सत्र खोजें, समान टेस्ट की तुलना करें और प्रगति देखें।|टेम्पलेट और दोहराए गए सत्र|स्प्रिंट टेम्पलेट या अपनी दूरी चुनें। सहेजा सेटअप फिर इस्तेमाल करें।|CSV, कार्ड और वीडियो|डेटा निर्यात करें, परिणाम कार्ड साझा करें या समय ओवरले वाला वीडियो बनाएँ।|वायरलेस और ऑफ़लाइन टाइमिंग|समर्थित स्थानीय कनेक्शन से पास के फ़ोन जोड़ें। परिणाम सहेजें और ऑनलाइन होने पर समर्थित डेटा सिंक करें।',
'beta':'विकास में|आपके प्रशिक्षण का अगला अध्याय।|Apple Watch से शुरुआत और रनिंग डायनेमिक्स। आड़े फ़ोन से सोलो स्प्रिंट। फुटबॉल के लिए 5-10-5 और आगे-पीछे दौड़ जैसी चपलता ड्रिल।|इन सुविधाओं की वास्तविक उपकरणों और मैदान पर जाँच चल रही है। ये सार्वजनिक ऐप में अभी नहीं हैं। रिलीज़ की तारीख तय नहीं है।|विकास पूर्वावलोकन देखें',
'founder':'ट्रैक पर जन्मा|इस्तेमाल करने वाले खिलाड़ी ने बनाया।|Sondre Guttormsen ओलंपिक पोल वॉल्टर और TrackSpeed के संस्थापक व डेवलपर हैं। लक्ष्य है रोज़ के प्रशिक्षण में दोहराए जा सकने वाले स्प्रिंट टेस्ट को आसान बनाना।|संस्थापक से मिलें|पोल वॉल्ट में प्रतिस्पर्धा करते Sondre Guttormsen',
'faq':'पहली दौड़ से पहले।|क्या एक ही फ़ोन से काम होगा?|हाँ। Solo Laps एक कैमरा लाइन को बार-बार पार करना रिकॉर्ड करता है। अलग-अलग शुरुआत और फ़िनिश के लिए जुड़े हुए फ़ोन चाहिए। आड़े कैमरे से सोलो स्प्रिंट और चपलता मोड अभी विकास में हैं।|क्या Wi-Fi या इंटरनेट चाहिए?|समर्थित स्थानीय कनेक्शन बिना इंटरनेट टाइमिंग कर सकते हैं। Wi-Fi Aware के लिए अनुकूल हार्डवेयर और सॉफ़्टवेयर चाहिए; Bluetooth भी एक विकल्प है। क्लाउड सुविधाओं के लिए इंटरनेट चाहिए।|यह कितना सटीक है?|परिणाम फ़्रेम दर, रोशनी, फ़ोन की स्थिति, स्टार्ट विधि और घड़ियों के सिंक पर निर्भर हैं। दशमलव अंकों की संख्या सटीकता की गारंटी नहीं है। स्थिर सेटअप रखें और फ़ोटो जाँचें। TrackSpeed प्रशिक्षण के लिए है, आधिकारिक प्रतियोगिता टाइमिंग के लिए नहीं।|क्या Apple Watch या Android पर काम करता है?|यहाँ वर्णित सार्वजनिक ऐप iPhone और iPad के लिए है। Watch, आड़े कैमरे की चपलता और Android विकास में हैं। सभी प्लेटफ़ॉर्म पर समान सुविधाओं का वादा नहीं है।|TrackSpeed की कीमत क्या है?|डाउनलोड मुफ़्त है, ऐप में खरीदारी उपलब्ध है। अपने क्षेत्र के प्लान, कीमत, ट्रायल पात्रता और सुविधाएँ ऐप में देखें।',
'cta':'अगले सत्र में साथ लाएँ|लाइन तय करें। अपना सर्वश्रेष्ठ दें।|अगला प्रशिक्षण सत्र शुरुआत की अच्छी जगह है।|iPhone और iPad · ऐप में खरीदारी',
'footer':'आपकी मेहनत के लिए स्प्रिंट टाइमिंग।|डेवलपर के और ऐप|Watch और आड़े कैमरे की चपलता: विकास में।'})

save('ar',{
'meta':'توقيت العدو. بهاتفك.|توقيت تلقائي، بوابات لاسلكية، لفات فردية، مراجعة الصور، ملفات الرياضيين وسجل الجلسات. تعرّف أيضًا إلى ميزات Watch والرشاقة قيد التطوير.',
'nav':'كل الميزات|تنزيل TrackSpeed|إغلاق القائمة|استكشف|دليل الميزات باللغة الإنجليزية',
'hero':'للتدريب بين المنافسات|توقيت العدو.|من هاتفك.|حوّل الهواتف التي تملكها إلى نظام توقيت. سجّل الانطلاق والمقاطع والوصول، وتابع تقدمك محاولة بعد أخرى.|اختر إعدادك|لـ iPhone وiPad · تنزيل مجاني ومشتريات داخل التطبيق|طوّره الرياضي الأولمبي Sondre Guttormsen|يعرض TrackSpeed عدوًا بانطلاق طائر مع صور البداية والنهاية|داخل TrackSpeed|زمن يمكنك العودة للتحقق منه.|تدريب العدو / الانطلاق الطائر / الاقتراب / اختبارات الفريق',
'facts':'هاتف للفات الفردية|هواتف للبوابات المتصلة|طرق لبدء العدو',
'modes':'جلستك. إعدادك.|توقيت يناسب تدريبك.|تدرّب بمفردك، أو اربط البوابات، أو استكشف ما نطوّره للمرحلة المقبلة.|رسم توضيحي للمسار، لا يعكس المقياس الحقيقي|البداية|مقطع|النهاية|هاتف|دوران|المنتصف|خط اللفة|قيد التطوير|متاح على iOS|ساعة',
'gates':'بوابات متصلة|جلسة واحدة. كل المقاطع.|ضع الهواتف عند البداية والنهاية، وأضف هاتفًا لمقطع وسيط لرؤية تغير السرعة على طول المسار.|قس المسار وثبّت كل هاتف في مكانه.|انضم إلى الجلسة نفسها وانتظر جاهزية كل البوابات.|اركض ثم راجع الزمن وصور العبور معًا.|هاتفان أو أكثر · مسار مقاس · حوامل ثابتة',
'solo':'لفات فردية|أنت وهاتف واحد.|ضع الكاميرا عند خط تعبره مرارًا. يبدأ العبور الأول الجلسة، ويسجل كل عبور لاحق لفة وصورة.|ثبّت الهاتف بجانب خط واضح.|اختر Solo Laps وتحقق من صورة الكاميرا.|اعبر الخط نفسه في كل لفة أو عودة.|هاتف واحد · عبور متكرر للخط نفسه',
'watch':'Apple Watch|جلستك على معصمك.|نطوّر الانطلاق من الساعة وعرض النتائج وديناميكيات الجري. يربط iPhone المقترن الساعة بجلسة التوقيت.|للانطلاق بالساعة، أقرنها بهاتف iPhone المضيف عند البداية.|استخدم هواتف أخرى للنهاية والمقاطع الاختيارية.|راجع الزمن ومقاييس الحركة المتاحة.|معاينة تطوير · ليست في التطبيق العام بعد',
'agility':'رشاقة وعدو فردي|كاميرا واحدة. التمرين كاملًا.|نطوّر التوقيت بالوضع الأفقي للانطلاق الثابت والطائر، واختبار 5-10-5 والذهاب والإياب. أبقِ المسار المقاس كاملًا ضمن الصورة.|لاختبار 5-10-5، ضع ثلاثة خطوط تفصل بينها 5 ياردات.|ابدأ من المنتصف، المس الخطين الخارجيين ثم عد إلى المنتصف.|العودة الأولى عبر المنتصف زمن مقطع. تحقّق من لمس الخطين بالفيديو.|معاينة تطوير · حامل ثلاثي ومراجعة الدوران بالفيديو',
'evidence':'أكثر من رقم|شاهد ما أوقف الساعة.|يحدد اكتشاف عبور الكاميرا تلقائيًا البداية والنهاية. افتح الصور، وتحقق من الخط، واحتفظ بالنتيجة في الجلسة.|اكتشاف تلقائي لعبور الخط|صور البداية والمقاطع والنهاية|مراجعة الصور وتعديل الزمن|كيف يعمل التوقيت|لقطة من التطبيق ببيانات جلسة توضيحية',
'starts':'اختر طريقة انطلاقك|خمس طرق للبدء.|اختر نقطة بداية الزمن المناسبة للاختبار. قارن نتائج تستخدم طريقة الانطلاق نفسها.|انطلاق طائر|اكتسب السرعة قبل البوابة الأولى. يبدأ المقطع المقاس عند عبور خط البداية.|رفع الإصبع|اضغط شاشة هاتف البداية. يبدأ الزمن عند رفع إصبعك.|عد تنازلي|ينتهي العد بإشارة صوتية. يبدأ الزمن مع الإشارة ويشمل استجابتك.|أمر صوتي|اتبع أوامر الانطلاق المنطوقة. يبدأ التوقيت عند GO.|انطلاق داخل الصورة|قف عند خط الكاميرا الأمامية لهاتف البداية، ثم اعبر الخط الظاهر لبدء التوقيت.',
'workflow':'من المحاولة الأولى إلى الجلسة المقبلة|تدريبك في مكان واحد.|استكشف كل الميزات|المقاطع ومتوسط السرعة|قس المحاولة كاملة وأجزاءها، وشاهد متوسط السرعة للمسافة المقاسة.|الرياضيون والفرق|اربط المحاولات بملفات الرياضيين ونظّم جلسات المجموعة.|السجل والأرقام الشخصية|ابحث عن الجلسات السابقة، وقارن الاختبارات المتطابقة، وتابع التقدم.|قوالب وجلسات متكررة|اختر قالب عدو أو مسافة مخصصة، وأعد استخدام إعداد محفوظ.|CSV وبطاقات وفيديو|صدّر البيانات أو شارك بطاقة نتيجة أو أنشئ فيديو مع عرض الزمن.|توقيت لاسلكي ودون إنترنت|اربط الهواتف القريبة باتصالات محلية مدعومة. احفظ النتائج وزامن البيانات المتوافقة عند الاتصال بالإنترنت.',
'beta':'قيد التطوير|الفصل القادم من تدريبك.|انطلاق Apple Watch وديناميكيات الجري. عدو فردي والهاتف أفقي. اختبارات رشاقة لكرة القدم، منها 5-10-5 والذهاب والإياب.|تخضع هذه الميزات لاختبارات فعلية وليست في التطبيق العام بعد. لا يوجد موعد إصدار مُعلن.|استكشف معاينة التطوير',
'founder':'وُلد على المضمار|صمّمه رياضي يستخدمه.|Sondre Guttormsen رياضي أولمبي في القفز بالزانة، ومؤسس TrackSpeed ومطوّره. هدفه عملي: تسهيل اختبارات العدو القابلة للتكرار في التدريب اليومي.|تعرّف إلى المؤسس|Sondre Guttormsen يتنافس في القفز بالزانة',
'faq':'قبل محاولتك الأولى.|هل يكفي هاتف واحد؟|نعم. يسجل Solo Laps العبور المتكرر لخط كاميرا واحد. تستخدم مواقع البداية والنهاية المنفصلة هواتف متصلة. العدو والرشاقة بكاميرا أفقية واحدة ما زالا قيد التطوير.|هل أحتاج إلى Wi-Fi أو الإنترنت؟|يمكن للاتصالات المحلية المدعومة قياس الزمن دون إنترنت. يتطلب Wi-Fi Aware أجهزة وبرامج متوافقة، وBluetooth خيار آخر. تحتاج ميزات السحابة إلى اتصال.|ما مدى الدقة؟|تعتمد على معدل الإطارات والإضاءة والموضع وطريقة الانطلاق وتزامن الساعات. عدد المنازل العشرية لا يضمن الدقة. ثبّت الإعداد وراجع صور العبور. TrackSpeed للتدريب، وليس للتوقيت الرسمي للمنافسات.|هل يعمل مع Apple Watch أو Android؟|التجربة العامة المعروضة هنا لـ iPhone وiPad. ميزات الساعة والرشاقة الأفقية وAndroid قيد التطوير، ولا نعد بتطابق الميزات على كل المنصات.|كم تبلغ تكلفة TrackSpeed؟|التنزيل مجاني مع مشتريات داخل التطبيق. راجع التطبيق للاطلاع على الخطط والأسعار وأهلية التجربة والميزات المتاحة في منطقتك.',
'cta':'خذه إلى جلستك المقبلة|حدّد الخط. قدّم أفضل ما لديك.|جلستك التدريبية المقبلة بداية مناسبة.|iPhone وiPad · مشتريات داخل التطبيق',
'footer':'توقيت عدو للجهد الذي تبذله.|المزيد من المطوّر|الساعة والرشاقة الأفقية: قيد التطوير.'})

save('tr',{
'meta':'Sprint zamanlaması. Telefonunuzla.|Otomatik sprint ölçümü, kablosuz kapılar, solo turlar, fotoğraf inceleme, sporcu profilleri ve seans geçmişi. Watch ve çeviklik geliştirmelerini de keşfedin.',
'nav':'Tüm özellikler|TrackSpeed’i indir|Menüyü kapat|Keşfet|Özellik rehberi İngilizcedir',
'hero':'Yarışmalar arasındaki emek için|Sprint zamanlaması.|Telefonunuzla.|Mevcut telefonlarınızı bir zamanlama sistemine dönüştürün. Başlangıçları, ara dereceleri ve bitişleri kaydedin. Gelişiminizi koşu koşu izleyin.|Kurulumunu seç|iPhone ve iPad · Ücretsiz indirme, uygulama içi satın alma|Olimpiyat sporcusu Sondre Guttormsen tarafından geliştirildi|TrackSpeed’de uçuş başlangıçlı sprint ve başlangıç-bitiş fotoğrafları|TrackSpeed’den bir görünüm|Dönüp kontrol edebileceğiniz bir süre.|Sprint antrenmanı / Uçuş başlangıcı / Yaklaşma koşuları / Takım testleri',
'facts':'telefonla solo turlar|telefonla bağlı kapılar|farklı sprint başlangıcı',
'modes':'Seansınız. Kurulumunuz.|Antrenmanınıza uygun zamanlama.|Tek başınıza çalışın, kapıları bağlayın veya geliştirdiğimiz özellikleri keşfedin.|Örnek parkur çizimi, ölçekli değildir|Başlangıç|Ara derece|Bitiş|Telefon|Dönüş|Orta|Tur çizgisi|Geliştiriliyor|iOS’ta mevcut|Saat',
'gates':'Bağlı kapılar|Tek seans. Her ara derece.|Başlangıç ve bitişe telefon yerleştirin. Hızın parkur boyunca değişimini görmek için ara noktaya bir telefon ekleyin.|Parkuru ölçün ve telefonları sabitleyin.|Aynı seansa katılın ve tüm kapılar hazır olana kadar bekleyin.|Koşun, ardından süreyi ve geçiş fotoğraflarını birlikte inceleyin.|2+ telefon · Ölçülmüş parkur · Sabit tutucular',
'solo':'Solo turlar|Siz ve tek telefon.|Kamerayı tekrar tekrar geçeceğiniz çizgiye yerleştirin. İlk geçiş seansı başlatır; sonraki geçişler tur ve fotoğraf kaydeder.|Telefonu belirgin bir çizginin yanına sabitleyin.|Solo Laps’i seçip kamera görüntüsünü kontrol edin.|Her turda veya dönüşte aynı çizgiyi geçin.|1 telefon · Aynı çizgiden tekrarlanan geçişler',
'watch':'Apple Watch|Seansınız bileğinizde.|Watch başlangıçları, sonuç gösterimi ve koşu dinamikleri geliştiriyoruz. Eşlenmiş iPhone, saati zamanlama seansına bağlar.|Watch başlangıçları için saati ana/başlangıç iPhone’una eşleyin.|Bitiş ve isteğe bağlı ara noktalar için diğer telefonları kullanın.|Süreyi ve mevcut hareket ölçümlerini inceleyin.|Geliştirme önizlemesi · Genel uygulamada henüz yok',
'agility':'Çeviklik ve solo sprint|Tek kamera. Bütün çalışma.|Yatay ölçüm; sabit ve uçuş başlangıçları, 5-10-5 ve gidiş-dönüş koşuları için geliştiriliyor. Ölçülen parkurun tamamı görünmeli.|5-10-5 için aralarında 5 yard olan üç çizgi işaretleyin.|Ortadan başlayın, iki dış çizgiye dokunun ve ortaya dönün.|Ortadan ilk dönüş geçişi ara derecedir. İki çizgi temasını da videodan kontrol edin.|Geliştirme önizlemesi · Tripod ve dönüşlerin video incelemesi',
'evidence':'Bir sayıdan fazlası|Saati neyin durdurduğunu görün.|Otomatik kamera geçişleri başlangıç ve bitişi kaydeder. Fotoğrafları açın, çizgiyi kontrol edin ve sonucu seansla birlikte saklayın.|Otomatik çizgi geçiş algılama|Başlangıç, ara nokta ve bitiş görüntüleri|Fotoğraf inceleme ve süre düzeltme|Zamanlama nasıl çalışır?|Örnek seans verileriyle uygulama görüntüsü',
'starts':'Başlangıcınızı seçin|Başlamak için beş yol.|Testinize uygun başlangıç anını seçin. Aynı başlangıç yöntemiyle kaydedilen sonuçları karşılaştırın.|Uçuş başlangıcı|İlk kapıdan önce hızlanın. Başlangıç çizgisini geçince ölçülen bölge başlar.|Dokunmayı bırakma|Başlangıç telefonunun ekranına basılı tutun. Parmağı kaldırmak süreyi başlatır.|Geri sayım|Geri sayım sesli işaretle biter. Süre işaretle başlar ve tepkinizi içerir.|Sesli komut|Sesli başlangıç komutlarını izleyin. Süre GO ile başlar.|Kamera içi başlangıç|Başlangıç telefonunun ön kamera çizgisinde durun. Ekrandaki çizgiyi geçerek başlayın.',
'workflow':'İlk tekrardan sonraki seansa|Antrenmanınız bir arada.|Tüm özellikleri keşfet|Ara dereceler ve ortalama hız|Tüm koşuyu ve bölümlerini ölçün. Ölçülen mesafedeki ortalama hızı görün.|Sporcular ve takımlar|Koşuları sporcu profillerine atayın, grup seanslarını düzenli tutun.|Geçmiş ve kişisel rekorlar|Eski seansları bulun, eşleşen testleri karşılaştırın ve gelişimi izleyin.|Şablonlar ve tekrar seansları|Sprint şablonu veya kendi mesafenizi seçin. Kaydedilen kurulumu yeniden kullanın.|CSV, kartlar ve video|Verileri dışa aktarın, sonuç kartı paylaşın veya zaman katmanlı video oluşturun.|Kablosuz ve çevrimdışı ölçüm|Yakındaki telefonları desteklenen yerel bağlantılarla birleştirin. Sonuçları kaydedip uygun verileri çevrimiçi olduğunuzda eşitleyin.',
'beta':'Geliştiriliyor|Antrenmanınızın sonraki bölümü.|Apple Watch başlangıçları ve koşu dinamikleri. Yatay solo sprint. 5-10-5 ve gidiş-dönüş koşuları dahil futbol için çeviklik testleri.|Bu özellikler fiziksel olarak test ediliyor ve genel uygulamada henüz bulunmuyor. Çıkış tarihi sözü verilmiyor.|Geliştirme önizlemesini incele',
'founder':'Pistte doğdu|Onu kullanan bir sporcu yaptı.|Sondre Guttormsen, Olimpik sırıkla atlama sporcusu ve TrackSpeed’in kurucusu ve geliştiricisidir. Amacı, tekrarlanabilir sprint testlerini günlük antrenmana daha kolay taşımaktır.|Kurucuyla tanışın|Sırıkla atlamada yarışan Sondre Guttormsen',
'faq':'İlk koşunuzdan önce.|Tek telefon kullanabilir miyim?|Evet. Solo Laps aynı kamera çizgisinden tekrarlanan geçişleri kaydeder. Ayrı başlangıç ve bitiş noktaları bağlı telefonlar kullanır. Yatay tek kamera sprint ve çeviklik modları geliştiriliyor.|Wi-Fi veya internet gerekli mi?|Desteklenen yerel bağlantılar internetsiz ölçüm yapabilir. Wi-Fi Aware uyumlu donanım ve yazılım gerektirir; Bluetooth da bir seçenektir. Bulut özellikleri bağlantı gerektirir.|Ne kadar doğru?|Kare hızı, ışık, konum, başlangıç yöntemi ve saat eşitlemesine bağlıdır. Ondalık basamak sayısı doğruluk garantisi değildir. Sabit kurulum kullanın ve geçiş fotoğraflarını inceleyin. TrackSpeed antrenman içindir, resmî yarış zamanlaması için değildir.|Apple Watch veya Android ile çalışır mı?|Burada anlatılan genel uygulama iPhone ve iPad içindir. Watch özellikleri, yatay çeviklik ve Android geliştiriliyor. Platformlar arasında aynı özellikler vaat edilmiyor.|TrackSpeed’in ücreti nedir?|Uygulama ücretsiz indirilir, uygulama içi satın alma vardır. Bölgenizdeki planları, fiyatları, deneme uygunluğunu ve özellikleri uygulamadan kontrol edin.',
'cta':'Sonraki seansa götürün|Çizgiyi belirle. Elinden geleni yap.|Sonraki antrenmanınız başlamak için iyi bir yer.|iPhone ve iPad · Uygulama içi satın alma',
'footer':'Verdiğiniz emek için sprint zamanlaması.|Geliştiriciden daha fazlası|Watch ve yatay çeviklik: geliştiriliyor.'})
