'use client';
import {useState} from 'react';
import {ArrowUpIcon, LightningBoltIcon, MixerHorizontalIcon} from '@radix-ui/react-icons';

const modes=[{id:'height',label:'Height',icon:ArrowUpIcon},{id:'rsi',label:'RSI',icon:LightningBoltIcon},{id:'sides',label:'Left / right',icon:MixerHorizontalIcon}] as const;
type Mode=typeof modes[number]['id'];
export default function JumpDemo(){
  const [mode,setMode]=useState<Mode>('height');
  return <div className="overflow-hidden rounded-[32px] border border-[#dce2e3] bg-white shadow-[0_24px_60px_-45px_#344b5066]">
    <div className="border-b border-[#e3e7e8] px-4 py-5 sm:px-8"><div role="group" aria-label="Example result type" className="jump-glass inline-flex max-w-full gap-1 rounded-full p-1">{modes.map(({id,label,icon:Icon})=><button key={id} type="button" aria-pressed={mode===id} aria-controls="jump-demo-result" onClick={()=>setMode(id)} className={`flex min-h-11 items-center justify-center gap-2 rounded-full px-3 text-sm font-medium transition-colors sm:px-5 ${mode===id?'bg-[#234f58] text-white shadow-sm':'text-[#4d6268] hover:bg-white'}`}><Icon aria-hidden="true" className="hidden size-4 min-[360px]:block"/>{label}</button>)}</div></div>
    <div id="jump-demo-result" aria-live="polite" aria-atomic="true" className="grid gap-10 p-6 sm:p-10 md:min-h-[370px] md:grid-cols-[.85fr_1.15fr] md:items-center">
      <div><p className="jump-eyebrow">{mode==='height'?'Vertical jump':mode==='rsi'?'Reactive strength':'Single-leg comparison'}</p><p className="mt-5 text-6xl font-semibold tracking-[-.055em] tabular-nums">{mode==='height'?'34.2':mode==='rsi'?'1.58':'8.2'} <span className="text-2xl font-normal tracking-normal">{mode==='height'?'cm':mode==='rsi'?'m/s':'%'}</span></p><p className="mt-4 max-w-xs leading-7 text-[#536369]">{mode==='height'?'Your height after landing, with flight time and estimated takeoff velocity.':mode==='rsi'?'Jump height divided by the ground contact immediately before takeoff.':'Compare matched jumps on each leg. Here, the right leg jumped higher.'}</p><p className="mt-5 text-xs text-[#718086]">Illustrative data · not a live measurement</p></div>
      {mode==='height'?<div><div className="relative rounded-3xl bg-[#f0f4f5] p-6"><svg viewBox="0 0 400 155" role="img" aria-label="Illustrative jump trajectory from takeoff to landing" className="w-full"><path d="M15 135H385M15 85H385M15 35H385" stroke="#d8e1e4" fill="none"/><path d="M20 135Q200 -88 380 135" stroke="#315f68" strokeWidth="3" fill="none"/><circle cx="200" cy="23.5" r="6" fill="#315f68"/><path d="M200 35V135" stroke="#74969f" strokeDasharray="4 5"/></svg><div className="mt-2 flex justify-between text-xs text-[#536369]"><span>Takeoff</span><span>Landing</span></div></div><div className="mt-5 grid grid-cols-2 divide-x divide-[#dce2e3]"><Metric label="Flight time" value="528 ms"/><Metric label="Takeoff velocity" value="2.59 m/s"/></div></div>
      :mode==='rsi'?<div><div className="rounded-3xl bg-[#f0f4f5] p-6"><div className="mb-6 flex justify-between text-sm"><span>Contact → flight</span><span className="text-[#536369]">One rebound</span></div><div className="flex h-16 gap-2" aria-hidden="true"><div className="flex-[.216] rounded-xl bg-[#345d66]"/><div className="flex-[.528] rounded-xl border border-[#c0d3d9] bg-[#dce8ec]"/></div><div className="mt-4 flex justify-between text-xs text-[#536369]"><span>216 ms contact</span><span>528 ms flight</span></div></div><div className="mt-5 grid grid-cols-2 divide-x divide-[#dce2e3]"><Metric label="Jump height" value="34.2 cm"/><Metric label="Ground contact" value="216 ms"/></div><p className="mt-4 text-center text-xs text-[#718086]">Reactive RSI and RSI-modified are separate metrics.</p></div>
      :<div><div className="rounded-3xl bg-[#f0f4f5] px-8 pb-5 pt-7"><div className="flex h-40 items-end justify-center gap-8" aria-hidden="true"><div className="flex h-[91.8%] w-20 items-start justify-center rounded-t-xl bg-[#cedde2] pt-4 font-mono text-sm">19.0</div><div className="flex h-full w-20 items-start justify-center rounded-t-xl bg-[#345d66] pt-4 font-mono text-sm text-white">20.7</div></div><div className="flex justify-center gap-8 border-t border-[#b9cdd3] pt-3 text-center text-sm"><span className="w-20">Left</span><span className="w-20">Right</span></div></div><div className="mt-5 grid grid-cols-2 divide-x divide-[#dce2e3]"><Metric label="Left jump" value="19.0 cm"/><Metric label="Right jump" value="20.7 cm"/></div><p className="mt-4 text-center text-xs text-[#718086]">Difference relative to the higher jump.</p></div>}
    </div>
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="px-3 text-center"><p className="text-xs text-[#536369]">{label}</p><p className="mt-1 font-mono text-lg font-medium">{value}</p></div>;}
