import Link from 'next/link';
import type {Metadata} from 'next';
import JumpLegal from '@/components/jump/JumpLegal';
export const metadata:Metadata={title:'Delete your TrackJump account',description:'Permanently delete your TrackJump account and private cloud recordings from Profile in the iPhone app.',alternates:{canonical:'https://mytrackspeed.com/jump/delete-account'}};
export default function Page(){return <JumpLegal title="Delete your account" intro="You can permanently delete your TrackJump account in the app, without contacting support.">
<h2>Delete in the iPhone app</h2><ol className="list-decimal space-y-3 pl-6"><li>Open TrackJump and select <strong>Profile</strong>.</li><li>Log in to the account you want to delete.</li><li>Choose <strong>Delete account</strong> under Your data.</li><li>Read the subscription notice, confirm that deletion is permanent, and complete the deletion.</li></ol><p className="mt-6"><a href="trackjump://account/delete">Open account deletion in TrackJump</a></p>
<h2>What is deleted</h2><p>Your active login account, owned athlete profiles, jump results and private cloud recordings are removed. The app also removes the matching local account archive on the iPhone that performs deletion. Your separate TrackSpeed account is unaffected. See the <Link href="/jump/privacy">Privacy Policy</Link> for retained operational records, provider backups and offline devices.</p>
<h2>Before you confirm</h2><p>Use <strong>Profile → Export all data</strong> if you need a copy. Deletion cannot be undone. Copies you shared or saved in Photos, Files or another app are not removed automatically. Remove those copies and any old offline installations separately if you no longer want them.</p><p>Deleting your account does not cancel billing through Apple. <a href="https://apps.apple.com/account/subscriptions">Manage or cancel your subscription</a> to prevent future charges. You can delete your account immediately without waiting for the subscription to expire.</p>
<h2>Sign in with Apple</h2><p>The deletion screen can reconnect to Apple to revoke authorization. If revocation cannot complete, TrackJump still deletes the account and explains how to remove its authorization from your Apple Account. In iPhone Settings, open your name, Sign in with Apple, then TrackJump and remove it.</p>
<h2>No account?</h2><p>Guest tests stay on your iPhone. You can export them and remove the app to erase its local data. Any exports saved outside the app remain until you delete them there.</p>
<h2>Having trouble?</h2><p>Try logging in again and retry deletion if the app reports an interruption. If you cannot access the app or your email, contact <a href="mailto:support@mytrackspeed.com?subject=TrackJump%20account%20access">support@mytrackspeed.com</a>. Do not send passwords or private videos. Support is an alternative for access problems, not a requirement for ordinary in-app deletion.</p>
</JumpLegal>}
