import Link from 'next/link';
import type {Metadata} from 'next';
import JumpLegal from '@/components/jump/JumpLegal';
export const metadata:Metadata={title:'TrackJump Privacy Policy',description:'How TrackJump handles jump recordings, athlete profiles, accounts and private backups.',alternates:{canonical:'https://mytrackspeed.com/jump/privacy'}};
export default function Page(){return <JumpLegal updatedAt="September 8, 2026" title="Privacy Policy" intro="TrackJump is provided by Athlete Mindset Inc. This policy explains the data used by the TrackJump iPhone app and its optional cloud backup.">
<h2>What stays on your iPhone</h2><p>Jump recordings, detected body landmarks, measurements, athlete profiles and review edits are stored in the app. Camera and body-pose analysis runs on your device. You can test without creating an account. We do not use body markers to identify faces or establish a biometric identity.</p>
<h2>What we collect when you connect</h2><ul><li><strong>Account information:</strong> your account identifier, email address and any name you choose to share through email, Apple or Google sign-in.</li><li><strong>Athlete and fitness data:</strong> athlete names, sport, optional height and weight, jump measurements, test dates, leg selection, event timings and review notes when you choose cloud backup.</li><li><strong>Recordings and analysis:</strong> the videos and associated body-landmark data included in your private backup, including estimated head and hand landmarks and any audio already contained in videos you import.</li><li><strong>Support and security:</strong> messages you send to support and technical request information needed to operate and secure the service, such as IP addresses and authentication events.</li></ul><p>Role and discovery-source answers are optional and saved with your local preferences. You may leave body measurements blank. Weight does not change flight-time jump height or reactive strength index.</p>
<h2>Why we use it</h2><p>We use your information to provide jump analysis, save and sync your chosen data, authenticate your account, restore your progress, respond to support and prevent unauthorized access. We do not sell personal information, use your videos to train general-purpose AI models, or run advertising tracking in the TrackJump app.</p>
<h2>Service providers and location</h2><p>Supabase provides authentication, our database and private video storage. The TrackJump project is hosted in US East, North Virginia. Resend delivers email sign-in codes and processes the destination address and authentication-email content for that purpose. Google Firebase processes feedback you choose to submit and hosts the moderated ideas board. Apple and Google process sign-in information under their own privacy policies, and Apple handles App Store payments. Their services may process information in other locations. Choosing Apple&apos;s Hide My Email lets you use a relay address.</p><p>Camera analysis uses Apple frameworks and an on-device MediaPipe pose model. It does not send video to Google for pose processing. The current app does not include RevenueCat or PostHog analytics. If that changes, we will update this policy and request any required consent before enabling new uses.</p>
<h2>Feedback and the ideas board</h2><p>Bug reports and questions are private. A report can include your message, an optional reply email and screenshots you select. Technical details such as the app and iOS version, device model, screen and event are included only when you choose to share diagnostics. If you permit an idea to be shared, a moderator may publish a separate summary after review. Your reply email and attachments are not published.</p><p>A random app-installation identifier is hashed to prevent duplicate votes. A daily changing hash derived from the request IP address limits report and vote abuse; these quota records are scheduled to expire after 48 hours. Service providers may keep their own security logs. These identifiers are not used for advertising tracking.</p><p>Feedback can be sent without an account, so deleting a TrackJump account does not automatically identify and delete separate feedback. Contact <a href="mailto:support@mytrackspeed.com">support@mytrackspeed.com</a> with the report details to request correction or deletion. We retain feedback as needed to handle the request, maintain the moderated board and protect the service; we verify removal requests to protect other people&apos;s information.</p>
<h2>Subscriptions</h2><p>Apple processes your payment details; TrackJump does not receive your card number. StoreKit verifies subscription transactions and access on your device. When server purchase verification is enabled, our service receives and verifies Apple-signed transaction and subscription-status information, including product and transaction identifiers, purchase, expiry and revocation dates, and an app account token where present. We use these records to provide and restore access and prevent fraud. They may be linked to your TrackJump account. Deleting your TrackJump account does not cancel an Apple subscription.</p>
<h2>Sharing and other athletes</h2><p>Your recordings are private by default. Exporting a card or replay hands that file to the destination you select, whose privacy practices then apply. Only include another person&apos;s profile or recording when you have their permission and any required parent or guardian permission. A coach is responsible for authorized collection and sharing of their athletes&apos; information.</p>
<h2>Retention and deletion</h2><p>Local recordings remain until you delete them, delete the associated account data on that iPhone, or remove the app. Signing out preserves that account&apos;s separate local archive, including unsynced changes, for when you sign back in. Exported copies in Photos, Files or another app are outside TrackJump&apos;s control.</p><p>You can permanently delete your account in <strong>Profile → Delete account</strong>. This removes your active account, owned athlete records, results and private cloud recordings. It also clears the matching account archive on the iPhone making the request. Other offline devices may retain local copies until you remove the app or erase those copies. Provider backups and operational logs expire under their retention schedules; deleted data is not made available again through normal account use. Limited purchase-verification, account-ownership and deletion-prevention records may remain after account deletion to prevent replay or unauthorized reassignment of purchases and to handle security, disputes or accounting. These records are restricted to service operations and do not restore your deleted athlete records or recordings. We may retain other limited information where legally necessary for security, disputes or accounting.</p><p><Link href="/jump/delete-account">Read the account deletion instructions</Link>. If Apple token revocation cannot complete, the app still deletes your TrackJump account and explains how to disconnect Apple authorization in Settings.</p>
<h2>Your choices</h2><p>Use guest testing, omit optional information, export your data in Profile, manage camera and motion permissions in iPhone Settings, and delete your account in the app. Contact <a href="mailto:support@mytrackspeed.com">support@mytrackspeed.com</a> to request access, correction, deletion or other privacy rights that apply where you live. We verify requests to protect your information.</p>
<h2>Young athletes</h2><p>TrackJump accounts are for people aged 13 and older. People under 18 need a parent or guardian&apos;s permission. We do not knowingly create accounts for children under 13. If you believe a child has provided account information without appropriate permission, contact us so we can address it.</p>
<h2>This website and policy changes</h2><p>This section is hosted on the TrackSpeed website. Website cookies and analytics are covered by the <Link href="https://mytrackspeed.com/privacy">TrackSpeed website privacy policy</Link>. Material changes to TrackJump&apos;s data practices will be reflected here and, when appropriate, communicated in the app. The date above identifies this version.</p>
</JumpLegal>}
