import Link from 'next/link';
import type {Metadata} from 'next';
import JumpLegal from '@/components/jump/JumpLegal';
export const metadata:Metadata={title:'TrackJump Support',description:'Help with camera setup, body markers, vertical jump, RSI, accounts and subscriptions.',alternates:{canonical:'https://mytrackspeed.com/jump/support'}};
export default function Page(){return <JumpLegal updatedAt="September 8, 2026" title="TrackJump support" intro="Help with a better setup, understandable results and control of your account.">
<h2>Set up your camera</h2><p>Place your iPhone upright on a stable bench or tripod. Keep one athlete&apos;s whole body, both shoes, the landing area and space above the head visible. Use even lighting and avoid strong backlighting. The selfie camera lets you see the framing guidance.</p><p>Stand tall and still while the app calibrates. When it is ready, jump when you want — there is no start button or countdown for vertical jumps. A score appears after the landing is detected. Tap Finish to review your session.</p>
<h2>Body markers or indoor flicker</h2><p>Step back if your feet or head are outside the frame. Make sure the camera is stationary and your legs are not obscured. Some indoor lights pulse on camera, especially at high frame rates. TrackJump adjusts exposure automatically. If lights still pulse, use steadier lighting or daylight. Supported frame rates vary by camera and iPhone.</p>
<h2 id="measurement" className="scroll-mt-28">Understand the measurements</h2><p><strong>Jump height</strong> estimates the rise of your body&apos;s centre of mass from takeoff to apex. It is not box height, foot clearance or standing reach. Flight-time height assumes similar body position at takeoff and landing. Body-trajectory estimates depend on usable visual evidence.</p><p><strong>Reactive strength index (RSI)</strong> is jump height in metres divided by the preceding ground-contact time in seconds. It applies to a rebound with a visible preceding landing. A first standing jump does not have this contact-based RSI.</p><p><strong>RSI-modified</strong> divides height by the time from movement onset to takeoff. Keep it separate from reactive RSI. Comparison metrics use matched tests and methods; a difference between sides does not diagnose injury.</p><p>Automatic jump-type labels are suggestions you can review and correct. Missing or ambiguous evidence may leave a type unresolved or withhold a result. Independent physical validation is in progress; do not assume force-plate accuracy.</p>
<h2>Accounts and backup</h2><p>Testing works as a guest. Use Profile to create an account, log in, back up your results, export data or sign out. Separate local archives preserve each account&apos;s unsynced work. <Link href="/jump/delete-account">Delete your account</Link> in the app when you want it permanently removed.</p>
<h2>Plans and purchases</h2><p>Exact local plan prices appear in the app before payment. Use Profile to restore purchases or <a href="https://apps.apple.com/account/subscriptions">manage your Apple subscription</a>. If the store is unavailable, check your connection and try reloading the plans. Never send payment-card details to support.</p>
<h2>Contact us</h2><p>Email <a href="mailto:support@mytrackspeed.com?subject=TrackJump%20support">support@mytrackspeed.com</a>. Include your iPhone model, iOS version, TrackJump version, test type, camera direction and what happened. Only share recordings if you choose to and everyone shown has agreed. Never include a password, sign-in code or payment details.</p>
</JumpLegal>}
