import Image from "next/image";
import { ArrowRightIcon, CheckIcon, ExternalLinkIcon } from "@radix-ui/react-icons";
import { setRequestLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { getRevenueCatWebCheckoutConfigIssues, type ProCheckoutPlan } from "@/lib/revenuecat-web";
import { DownloadLink } from "@/components/DownloadLink";
import { Eyebrow, TextLink } from "@/components/marketing/Primitives";

export default async function ProPage({params}: {params: Promise<{locale: string}>}) {
  const {locale} = await params;
  setRequestLocale(locale);
  const webPlan = (["annual", "weekly"] as ProCheckoutPlan[]).find(plan => getRevenueCatWebCheckoutConfigIssues(plan).length === 0);
  return <div lang="en" dir="ltr">
    <section className="bg-[var(--bg-warm)] px-5 pb-20 pt-32 sm:px-8 lg:pb-28 lg:pt-40"><div className="marketing-container grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-start lg:gap-24">
      <div><Eyebrow>TrackSpeed Pro</Eyebrow><h1 className="marketing-page-title">Make every<br/>session count.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted">Connected timing, reviewable results and a training history that stays with you. Explore the Pro workflow and choose the offer available to you in TrackSpeed.</p><div className="mt-8"><DownloadLink store="ios" className="marketing-button">Get TrackSpeed<ArrowRightIcon className="size-4" aria-hidden="true"/></DownloadLink></div><p className="mt-4 text-xs leading-6 text-muted">Free to download · In-app purchases<br/>Available on iPhone and iPad</p><div className="mt-10"><TextLink href="/features">Explore the complete feature guide</TextLink></div></div>
      <aside className="rounded-2xl border border-[var(--border-light)] bg-white p-7 sm:p-10" aria-labelledby="plans-heading"><p className="mb-5 text-xs font-semibold uppercase tracking-wider text-[var(--brand)]">Your plan</p><h2 id="plans-heading" className="text-3xl font-medium tracking-tight">Find your current offer.</h2><p className="mt-5 text-sm leading-7 text-muted">Plans, prices and trial eligibility are shown in the app for your account and region. Review the renewal price and billing period before purchasing.</p><ul className="my-7 space-y-4">{["Multi-phone start, split and finish timing", "Session history and athlete profiles", "Photo review and video exports", "Tools for repeatable training sessions"].map(item=><li key={item} className="flex items-start gap-3 text-sm leading-6"><CheckIcon className="mt-1 size-4 shrink-0 text-[var(--brand)]" aria-hidden="true"/>{item}</li>)}</ul><p className="border-t border-[var(--border-light)] pt-5 text-xs leading-6 text-muted">Check the app for your current entitlement and supported devices.</p><a href="trackspeed://subscribe" className="marketing-button mt-7 w-full">Open plans in the app<ExternalLinkIcon className="size-4" aria-hidden="true"/></a><p className="mt-3 text-center text-xs leading-5 text-muted">Already installed? Open TrackSpeed to see your offer.</p>{webPlan && <div className="mt-7 border-t border-[var(--border-light)] pt-6"><Link href={`/checkout/pro?plan=${webPlan}`} className="inline-flex min-h-11 items-center gap-3 text-sm font-semibold text-[var(--brand)]">Continue on the web<ArrowRightIcon className="size-4" aria-hidden="true"/></Link><p className="mt-2 text-xs leading-6 text-muted">Create your TrackSpeed account, review the checkout terms, then sign in to the app with the same account.</p></div>}</aside>
    </div></section>
    <section className="marketing-section"><div className="marketing-container grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><figure className="overflow-hidden rounded-2xl border border-[var(--border-light)] bg-[var(--bg-warm)] px-8 pt-8 sm:px-16"><div className="mx-auto max-h-[490px] max-w-[310px] overflow-hidden rounded-t-2xl"><Image src="/product/session-history.png" alt="A TrackSpeed run saved with timing details and review options" width={1206} height={2622} sizes="310px" className="h-auto w-full"/></div><figcaption className="py-4 text-center text-[11px] text-muted">App screenshot with sample session data.</figcaption></figure><div><Eyebrow>Build a useful training record</Eyebrow><h2 className="marketing-heading">Keep the context.<br/>See the progress.</h2><p className="mt-6 text-base leading-8 text-muted">A personal best means more when the test is consistent. Keep your start method, distance, athlete and session together. Return to the crossing photos when you want to check a result.</p><div className="mt-7"><TextLink href="/technology">Understand the timing method</TextLink></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs text-muted"><Link href="/support" className="underline underline-offset-4">Purchase or restore help</Link><Link href="/terms" className="underline underline-offset-4">Terms & conditions</Link></div></div></div></section>
  </div>;
}
