import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRightIcon, ArrowTopRightIcon, CheckIcon, MobileIcon, PlayIcon} from '@radix-ui/react-icons';
import JumpFooter from '@/components/jump/JumpFooter';
import JumpDemo from '@/components/jump/JumpDemo';

export const metadata:Metadata={applicationName:'TrackJump',itunes:null,title:'TrackJump — Your jump. Your iPhone.',description:'Automatic vertical jump, reactive strength and single-leg testing. See the movement behind your numbers with TrackJump, from the TrackSpeed family.',alternates:{canonical:'https://mytrackspeed.com/jump'},openGraph:{title:'TrackJump — Your jump. Your iPhone.',description:'Jump height, RSI and left/right comparison. One iPhone. No extra hardware.',url:'https://mytrackspeed.com/jump',images:['/jump/share-image']},twitter:{card:'summary_large_image',title:'TrackJump — Your jump. Your iPhone.',description:'See the movement behind your numbers.',images:['/jump/share-image']}};
const tests=[['01','Vertical & max jump','Find your height. Build your benchmark.','Countermovement, squat and arm-swing jumps.'],['02','Reactive strength','Less time on the ground. More in the air.','Drop jumps and repeated rebounds, with contact time and RSI.'],['03','Left & right','Give both sides a clear picture.','Single-leg jumps, matched comparisons and percentage differences.']];

export default function JumpPage(){return <div className="jump-visual-page bg-[#f4f5f5] text-[#192b30]">
  <section className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-32 lg:grid-cols-[1fr_1.08fr] lg:gap-20 lg:px-10 lg:pb-28 lg:pt-40">
    <div><p className="mb-7 text-xs font-semibold uppercase tracking-[.2em] text-[#466970]">TrackJump / From the TrackSpeed family</p><h1 className="text-[clamp(3rem,6.5vw,5.5rem)] font-semibold leading-[1.02] tracking-[-.06em]">Your jump.<br/>Your iPhone.</h1><p className="mt-7 max-w-md text-lg leading-relaxed text-[#536369]">Measure your vertical. Understand your rebound. See the difference between left and right.</p><p className="mt-4 text-base text-[#536369]">Set down your iPhone. Step back. Jump.</p><a href="#explore" className="jump-primary mt-8 inline-flex items-center gap-3 rounded-full px-7 py-4 font-medium">Explore TrackJump <ArrowRightIcon aria-hidden="true"/></a><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-[#536369]"><span className="inline-flex items-center gap-2"><MobileIcon aria-hidden="true"/> iPhone only</span><span className="inline-flex items-center gap-2"><CheckIcon aria-hidden="true"/> No extra hardware</span></div></div>
    <figure className="relative mx-auto w-full max-w-[520px]"><div className="relative aspect-[2/3] overflow-hidden rounded-[36px] bg-[#c9cccd] shadow-[0_24px_65px_-35px_#35494c66]"><Image src="/jump/visuals/athlete-pose.png" width={1024} height={1536} sizes="(max-width: 768px) 90vw, 520px" preload alt="Illustration of an athlete jumping with hands on hips, with body markers aligned to the shoulders, hips, knees and ankles." className="h-full w-full object-cover"/><div className="absolute inset-0 bg-linear-to-b from-[#17242a55] via-transparent to-[#17242a22]"/><div className="absolute inset-x-6 top-6 flex items-center justify-between text-sm text-white"><span className="font-medium">TrackJump</span><span className="jump-glass rounded-full px-4 py-2 text-[#192b30]">Max jump</span></div><div className="jump-glass absolute inset-x-5 bottom-5 rounded-[24px] p-5 text-[#192b30]"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-medium">Jump height</p><p className="mt-1 text-4xl font-semibold tracking-tight">34.2 <span className="text-base font-normal">cm</span></p></div><a href="#explore" aria-label="Explore example jump results" className="jump-glass flex size-12 items-center justify-center rounded-full"><ArrowRightIcon className="size-5" aria-hidden="true"/></a></div><div className="mt-4 flex gap-2 border-t border-white/55 pt-3 text-xs"><span>Height</span><span aria-hidden="true">/</span><span>RSI</span><span aria-hidden="true">/</span><span>Left & right</span></div></div></div><figcaption className="mt-3 text-center text-xs text-[#617279]">Product illustration · example result</figcaption></figure>
  </section>
  <section id="how-it-works" className="scroll-mt-24 border-y border-[#dce2e3] bg-white py-20"><div className="mx-auto grid max-w-6xl gap-12 px-6 md:grid-cols-[.9fr_1.1fr] md:gap-20"><div><p className="jump-eyebrow">Ready when you are</p><h2 className="jump-heading mt-4">Less setup.<br/>More jumping.</h2><p className="mt-6 max-w-sm leading-7 text-[#536369]">Front or rear camera. A bench or tripod. TrackJump helps you get into position, then detects your jumps automatically.</p><Link href="/jump/support" className="mt-6 inline-flex items-center gap-2 text-sm font-medium underline underline-offset-4">The quick setup guide <ArrowTopRightIcon aria-hidden="true"/></Link></div><ol className="divide-y divide-[#dce2e3]">{[['Set it down','Keep your iPhone still, with your whole body and landing area in view.','01'],['Stand still','Body markers help with framing. Hold your position while the app calibrates.','02'],['Jump when ready','See your result after landing. Keep jumping to record more reps.','03']].map(([title,text,number])=><li key={number} className="flex gap-5 py-7 first:pt-0 last:pb-0"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-[#eef2f3] font-mono text-sm text-[#315f68]">{number}</span><div><h3 className="text-xl font-semibold tracking-tight">{title}</h3><p className="mt-2 max-w-sm leading-7 text-[#536369]">{text}</p></div></li>)}</ol></div></section>
  <section id="explore" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-24 lg:px-10"><div className="mb-12 flex flex-wrap items-end justify-between gap-6"><div><p className="jump-eyebrow">A closer look</p><h2 className="jump-heading mt-4">See what your jump<br/>can tell you.</h2></div><p className="max-w-xs leading-7 text-[#536369]">Explore example results for height, reactive strength and side-to-side comparison.</p></div><JumpDemo/></section>
  <section className="bg-[#e8edef] py-20"><div className="mx-auto grid max-w-6xl items-center gap-12 px-6 md:grid-cols-[1.1fr_1fr] md:gap-20"><figure className="rounded-[32px] border border-white bg-white/65 p-5 shadow-[0_16px_45px_-30px_#344b5066] sm:p-8"><div className="mb-6 flex items-center justify-between"><span className="text-sm font-medium">Your session</span><span className="text-xs text-[#536369]">3 jumps</span></div><div className="grid grid-cols-3 gap-3">{[31.8,34.2,33.1].map((value,i)=><div key={value}><div className={`relative aspect-[2/3] overflow-hidden rounded-2xl ${i===1?'ring-2 ring-[#315f68] ring-offset-4 ring-offset-[#f8fafa]':''}`}><Image src="/jump/visuals/athlete-pose.png" width={1024} height={1536} sizes="180px" alt="" className="h-full w-full object-cover"/><span className="absolute bottom-2 left-2 rounded-full bg-white/85 px-2 py-1 text-[10px]">Jump {i+1}</span></div><p className="mt-3 text-center font-mono text-sm">{value.toFixed(1)} <span className="text-xs text-[#536369]">cm</span></p></div>)}</div><figcaption className="mt-6 flex items-center justify-between gap-3 border-t border-[#dce2e3] pt-5"><span className="flex items-center gap-2 text-sm"><PlayIcon aria-hidden="true"/> A clip for every jump</span><span className="text-xs text-[#536369]">Example session</span></figcaption></figure><div><p className="jump-eyebrow">More than a number</p><h2 className="jump-heading mt-4">Every jump.<br/>Worth a replay.</h2><p className="mt-6 leading-7 text-[#536369]">Your jumps become individual clips, with their results alongside. Review takeoff and landing, compare reps, and share the moment.</p><p className="mt-4 text-sm leading-6 text-[#536369]">Camera estimates depend on lighting, framing and technique. The recording helps you see the movement behind the result.</p><Link href="/jump/support#measurement" className="mt-6 inline-flex items-center gap-2 text-sm font-medium underline underline-offset-4">Understand the measurements <ArrowTopRightIcon aria-hidden="true"/></Link></div></div></section>
  <section id="tests" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-24"><p className="jump-eyebrow">Find your test</p><h2 className="jump-heading mb-12 mt-4">One camera.<br/>Your whole jump profile.</h2>{tests.map(([number,title,heading,description])=><div key={number} className="grid gap-4 border-t border-[#dce2e3] py-8 md:grid-cols-[48px_1fr_1.1fr]"><span className="font-mono text-sm text-[#315f68]">{number}</span><h3 className="text-2xl font-medium tracking-tight">{title}</h3><div><p className="font-medium">{heading}</p><p className="mt-2 leading-7 text-[#536369]">{description}</p></div></div>)}</section>
  <section className="mx-auto mb-20 max-w-7xl px-6 lg:px-10"><div className="grid gap-10 rounded-[36px] bg-[#203e45] px-7 py-12 text-white sm:px-12 md:grid-cols-[1fr_.7fr] md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#c0d6dc]">The TrackSpeed family</p><h2 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">Your sprint. Your jump.<br/>Your next step forward.</h2><p className="mt-5 max-w-md leading-7 text-[#d2dfe2]">Two focused tools for athletes and coaches. Track your progress, one session at a time.</p><Link href="https://mytrackspeed.com/" className="mt-6 inline-flex items-center gap-3 rounded-full border border-white/30 px-6 py-3 text-sm font-medium transition-colors hover:bg-white/10">Meet TrackSpeed <ArrowTopRightIcon aria-hidden="true"/></Link></div><div className="rounded-3xl border border-white/20 bg-white/10 p-7"><h3 className="text-xl font-medium">TrackJump for iPhone</h3><p className="mt-3 text-sm leading-6 text-[#d2dfe2]">In development. Independent physical accuracy validation is in progress.</p><Link href="/jump/support" className="mt-6 inline-flex items-center gap-2 text-sm font-medium underline underline-offset-4">Questions? Get in touch <ArrowRightIcon aria-hidden="true"/></Link></div></div></section>
  <JumpFooter/>
</div>;}
